name: lualike
description: >
    A Lua-like scripting language for Dart, designed to be easy to embed and extend.
    It provides a simple REPL, supports Lua-like syntax, and allows for seamless integration with Dart code.
version: 0.0.1
repository: https://github.com/kingwill101/lualike
topics:
  - lua
  - scripting
  - interop
  - interpreter
  - repl

environment:
  sdk: ">=3.8.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  characters: ^1.4.1
  source_span: ^1.10.1
  crypto: ^3.0.6
  pointycastle: ^4.0.0

  path: ^1.9.1
  archive: ^4.0.7
  http: ^1.4.0
  yaml: ^3.1.3
  dart_console: ^4.1.2
  glob: ^2.1.3
  convert: ^3.1.2
  collection: ^1.19.1
  petitparser: ^7.0.0
  xrandom: ^0.7.2
  logging: ^1.3.0
  args: ^2.7.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0

funding:
  - https://www.buymeacoffee.com/kingwill101

executables:
    lualike: bin/main.dart
