name: lualike
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.8.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  characters: ^1.4.0
  source_span: ^1.10.1
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  # path: ^1.8.0

  path: any
  archive: ^4.0.3
  http: ^1.3.0
  yaml: ^3.1.3
  dart_console: ^1.2.0
  glob: ^2.1.3
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
