name: lualike
description: >
    A Lua-like scripting language for Dart, designed to be easy to embed and extend.
    It provides a simple REPL, supports Lua-like syntax, and allows for seamless integration with Dart code.
version: 0.0.1
repository: https://github.com/kingwill101/lualike
topics:
  - lua
  - scripting
  - interop
  - interpreter
  - repl

environment:
  sdk: ">=3.8.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  characters: ^1.4.0
  source_span: ^1.10.1
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  # path: ^1.8.0

  path: any
  archive: ^4.0.3
  http: ^1.3.0
  yaml: ^3.1.3
  dart_console: ^1.2.0
  glob: ^2.1.3
  convert: ^3.1.2
  petitparser: ^7.0.0
  xrandom: ^0.7.2
  logging: ^1.3.0
  args: ^2.7.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

funding:
  - https://www.buymeacoffee.com/kingwill101

executables:
    lualike: bin/main.dart
