#!/usr/bin/env zsh
# Compile a Lua script to a native binary via the Dart AOT backend.
#
# Usage:
#   zsh tool/aot_compile.sh script.lua [output]
set -eo pipefail

DIR="${0:A:h}"
BINARY="./build/cli/linux_x64/bundle/bin/main"
SCRIPT="$1"
OUTPUT="${2:-a.out}"

if [[ -z "$SCRIPT" ]]; then
  echo "Usage: $0 <script.lua> [output]"
  exit 1
fi

if [[ ! -f "$BINARY" ]]; then
  echo "FAIL: lualike binary not found at $BINARY"
  echo "Run 'just compile' first."
  exit 1
fi

SCRIPT_DIR="$(dirname "$SCRIPT")"
SCRIPT_BASE="$(basename "$SCRIPT" .lua)"
DART_OUT="$SCRIPT_DIR/${SCRIPT_BASE}_aot.dart"

echo "  emit Dart..."
"$BINARY" --ir --emit-dart "$SCRIPT" 2>/dev/null | sed -n '/^\/\/ Generated by lualike/,/^--- End/p' | sed '$d' | tail -n +2 > "$DART_OUT"

# Check we got something
if ! grep -q "Future<Value> _lua_fn_0" "$DART_OUT"; then
  echo "FAIL: no Lua function in Dart output"
  exit 1
fi

echo "  dart compile exe..."
dart compile exe "$DART_OUT" -o "$OUTPUT" 2>&1 | tail -1 || {
  echo "FAIL: dart compile exe"
  exit 1
}

echo "  run..."
if "$OUTPUT"; then
  echo "  ok"
else
  rc=$?
  echo "  exit $rc"
fi
