import 'package:flutter_test/flutter_test.dart';
import 'package:love2d/love2d.dart';

const String _compiledFragmentMetadataSource = '''
// This SkSL shader is autogenerated by spirv-cross.

float4 flutter_FragCoord;
uniform vec2 iResolution;
uniform float iTime;
uniform shader iChannel0;
uniform half2 iChannel0_size;

vec4 fragColor;

half4 main(float2 iFragCoord) {
  return fragColor;
}
''';

void main() {
  test(
    'compiled Flutter fragment metadata treats shader uniforms as samplers',
    () {
      final shader = LoveShader(
        pixelCode: _compiledFragmentMetadataSource,
        kind: LoveShaderKind.generic,
        flutterFragmentAssetKey: 'assets/shader_explorer/shaders/snow.glsl',
      );

      expect(shader.uniformDeclaration('iResolution')?.typeName, 'vec2');
      expect(shader.uniformDeclaration('iTime')?.typeName, 'float');
      expect(shader.uniformDeclaration('iChannel0')?.typeName, 'shader');
      expect(
        shader.uniformDeclaration('iChannel0')?.valueKind,
        LoveShaderUniformValueKind.sampler,
      );
      expect(shader.uniformDeclaration('iChannel0_size')?.typeName, 'half2');
      expect(
        shader.uniformDeclaration('iChannel0_size')?.valueKind,
        LoveShaderUniformValueKind.unknown,
      );
    },
  );
}
