import 'instruction.dart';
import 'opcode.dart';
import 'prototype.dart';
import 'ssa.dart';
import 'ssa_type_analysis.dart';

/// Emits Dart source from lualike IR using the existing Value runtime.
class LualikeIrToDart {
  LualikeIrToDart({
    required this.chunk,
  });

  final LualikeIrChunk chunk;

  final _buf = StringBuffer();
  int _nextIndex = 0;

  /// Generate a complete standalone Dart program (with main()).
  String generateStandalone() {
    _buf.clear();
    _nextIndex = 0;
    _writeln('// Generated by lualike.  Compile: dart compile exe <this-file>');
    _writeln('import \"dart:io\" show stdout;');
    _writeln('import \"package:lualike/src/runtime/lua_runtime.dart\";');
    _writeln('import \"package:lualike/src/ir/runtime.dart\";');
    _writeln('import \"package:lualike/src/value.dart\";');
    _writeln('import \"package:lualike/src/lua_string.dart\";');
    _writeln('import \"package:lualike/src/table_storage.dart\";');
    _writeln();

    _writeln('Value _mkTable() => Value(TableStorage());');
    _writeln();

    // Emit all prototypes recursively.
    final emitted = <String>[];
    _emitPrototype(chunk.mainPrototype, '_lua_fn_0', emitted);

    // Main driver
    _writeln('');
    _writeln('Future<void> main(List<String> cliArgs) async {');
    _writeln('  final rt = LualikeIrRuntime();');
    _writeln("  final env = rt.globals.get(\"_G\");");
    _writeln("  final envValue = env is Value ? env : Value(env);");
    _writeln("  final result = await _lua_fn_0(rt, <Value>[], [envValue], <Value>[]);");
    _writeln('  // result is the script return value; scripts print their own output.');
    _writeln('}');

    return _buf.toString();
  }

  /// Generate just the main Lua function (for embedding).
  String generateModule() {
    _buf.clear();
    _nextIndex = 0;
    _writeln('// Generated by lualike Dart lowering');
    _writeln('import \"package:lualike/src/value.dart\";');
    _writeln('import \"package:lualike/src/runtime/lua_runtime.dart\";');
    _writeln();
    _emitPrototype(chunk.mainPrototype, '_lua_fn_0', <String>[]);
    return _buf.toString();
  }

  void _emitPrototype(
    LualikeIrPrototype proto,
    String fname,
    List<String> emitted,
  ) {
    if (emitted.contains(fname)) return;
    emitted.add(fname);

    // Emit nested prototypes first.
    for (var i = 0; i < proto.prototypes.length; i++) {
      _emitPrototype(proto.prototypes[i], '${fname}_$i', emitted);
    }

    final ssa = LualikeIrSsaFunction.fromPrototype(proto).simplifyTrivialPhis();
    final ta = analyzeLualikeIrSsaTypes(proto, ssa);

    final rc = _maxRegister(proto) + 1;
    _writeln('Future<Value> $fname(LuaRuntime rt, List<Value> args, List<Value> upvals, List<Value> varargs) async {');
    _writeln('  final r = <Value>[];');
    _writeln('  for (var i = 0; i < $rc; i++) r.add(Value(null));');

    for (var i = 0; i < proto.paramCount; i++) {
      _writeln('  if ($i < args.length) r[$i] = args[$i];');
    }

    _writeln('  var pc = 0;');
    _writeln('  while (true) {');
    _writeln('    switch (pc) {');

    for (final ssaBlock in ssa.blocks) {
      for (final pc in ssaBlock.block.instructionPcs) {
        final inst = proto.instructions[pc];
        _emitCase(inst, proto, fname, emitted, pc);
      }
    }

    _writeln('    }');
    _writeln('  }');
    _writeln('}');
  }

  void _emitCase(
    LualikeIrInstruction inst,
    LualikeIrPrototype proto,
    String fname,
    List<String> emitted,
    int pc,
  ) {
    final next = pc + 1;
    final constants = proto.constants;

    void reg(int a, String expr) {
      _writeln('    case $pc:');
      _writeln('      r[$a] = $expr;');
      _writeln('      pc = $next;');
      _writeln('      break;');
    }

    void stmt(String code) {
      _writeln('    case $pc:');
      _writeln('      $code');
      _writeln('      pc = $next;');
      _writeln('      break;');
    }

    void unsupported([String info = '']) {
      stmt('throw UnsupportedError(\"${inst.opcode}$info\");');
    }

    int imm(int c, bool k) => k ? (c << 23) >> 23 : c;

    String constExpr(int index) {
      if (index < 0 || index >= constants.length) return 'Value(0)';
      return switch (constants[index]) {
        IntegerConstant(value: final v) => 'Value($v)',
        NumberConstant(value: final v) => 'Value(${_dl(v)})',
        NilConstant() => 'Value(null)',
        BooleanConstant(value: final v) => v ? 'Value(true)' : 'Value(false)',
        ShortStringConstant(value: final v) => 'Value(${_es(v)})',
        LongStringConstant(value: final v) => 'Value(${_es(v)})',
      };
    }

    String strKey(int index) {
      if (index < 0 || index >= constants.length) return 'null';
      final c = constants[index];
      final s = switch (c) {
        ShortStringConstant(value: final v) => v,
        LongStringConstant(value: final v) => v,
        _ => '',
      };
      if (s.isEmpty) return constExpr(index);
      return _es(s);
    }

    switch (inst) {
      case ABCInstruction(opcode: LualikeIrOpcode.move, a: final a, b: final b):
        reg(a, 'r[$b]');

      case ABCInstruction(opcode: LualikeIrOpcode.loadI, a: final a, b: final b):
        stmt('r[$a] = Value(${_se(b, 8)});');
      case AsBxInstruction(opcode: LualikeIrOpcode.loadI, a: final a, sBx: final sBx):
        stmt('r[$a] = Value($sBx);');

      case ABCInstruction(opcode: LualikeIrOpcode.loadF, a: final a, b: final b):
        stmt('r[$a] = Value(${_se(b, 8)}.0);');
      case AsBxInstruction(opcode: LualikeIrOpcode.loadF, a: final a, sBx: final sBx):
        stmt('r[$a] = Value($sBx.0);');

      case ABCInstruction(opcode: LualikeIrOpcode.loadFalse, a: final a):
        stmt('r[$a] = Value(false);');
      case ABCInstruction(opcode: LualikeIrOpcode.loadTrue, a: final a):
        stmt('r[$a] = Value(true);');
      case ABCInstruction(opcode: LualikeIrOpcode.loadNil, a: final a):
        stmt('r[$a] = Value(null);');

      case ABxInstruction(opcode: LualikeIrOpcode.loadK, a: final a, bx: final bx):
        stmt('r[$a] = ${constExpr(bx)};');

      case ABxInstruction(opcode: LualikeIrOpcode.closure, a: final a, bx: final bx):
        _emitClosure(a, bx, proto, fname, emitted, pc);

      // Arithmetic (register)
      case ABCInstruction(opcode: LualikeIrOpcode.add, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] + r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.sub, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] - r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.mul, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] * r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.div, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] / r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.mod, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] % r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.pow, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] ^ r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.idiv, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] // r[$c]');

      case ABCInstruction(opcode: LualikeIrOpcode.addI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = r[$b] + Value(${imm(c, k)});');
      case ABCInstruction(opcode: LualikeIrOpcode.subI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = r[$b] - Value(${imm(c, k)});');

      case ABCInstruction(opcode: LualikeIrOpcode.addK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] + ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.subK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] - ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.mulK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] * ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.divK, a: final a, b: final b, c: final c):
      case ABCInstruction(opcode: LualikeIrOpcode.modK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] % ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.powK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] ^ ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.idivK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] // ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.bandK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] & ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.borK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] | ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.bxorK, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] ^ ${constExpr(c)};');
      case ABCInstruction(opcode: LualikeIrOpcode.shlI, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] << Value($c);');
      case ABCInstruction(opcode: LualikeIrOpcode.shrI, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b] >> Value($c);');
        stmt('r[$a] = r[$b] / ${constExpr(c)};');

      // Bitwise
      case ABCInstruction(opcode: LualikeIrOpcode.band, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] & r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.bor, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] | r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.bxor, a: final a, b: final b, c: final c):
        reg(a, 'r[$b] ^ r[$c]');
      case ABCInstruction(opcode: LualikeIrOpcode.bnot, a: final a, b: final b):
        reg(a, '~r[$b]');
      case ABCInstruction(opcode: LualikeIrOpcode.shl, a: final a, b: final b, c: final c):
        unsupported(' << ');
      case ABCInstruction(opcode: LualikeIrOpcode.shr, a: final a, b: final b, c: final c):
        unsupported(' >> ');

      case ABCInstruction(opcode: LualikeIrOpcode.unm, a: final a, b: final b):
        reg(a, '-r[$b]');
      case ABCInstruction(opcode: LualikeIrOpcode.notOp, a: final a, b: final b):
        stmt('r[$a] = Value(!r[$b].isTruthy());');

      // Comparisons
      case ABCInstruction(opcode: LualikeIrOpcode.eq, a: final a, b: final b, c: final c):
        stmt('r[$a] = Value(r[$b] == r[$c]);');
      case ABCInstruction(opcode: LualikeIrOpcode.lt, a: final a, b: final b, c: final c):
        stmt('r[$a] = Value(r[$b] < r[$c]);');
      case ABCInstruction(opcode: LualikeIrOpcode.le, a: final a, b: final b, c: final c):
        stmt('r[$a] = Value(r[$b] <= r[$c]);');
      case ABCInstruction(opcode: LualikeIrOpcode.eqI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = Value(r[$b] == Value(${imm(c, k)}));');
      case ABCInstruction(opcode: LualikeIrOpcode.ltI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = Value(r[$b] < Value(${imm(c, k)}));');
      case ABCInstruction(opcode: LualikeIrOpcode.leI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = Value(r[$b] <= Value(${imm(c, k)}));');
      case ABCInstruction(opcode: LualikeIrOpcode.gtI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = Value(r[$b] > Value(${imm(c, k)}));');
      case ABCInstruction(opcode: LualikeIrOpcode.geI, a: final a, b: final b, c: final c, k: final k):
        stmt('r[$a] = Value(r[$b] >= Value(${imm(c, k)}));');
      case ABCInstruction(opcode: LualikeIrOpcode.eqK, a: final a, b: final b, c: final c):
        stmt('r[$a] = Value(r[$b] == ${constExpr(c)});');

      // Test / branch
      case ABCInstruction(opcode: LualikeIrOpcode.test, a: final a, k: final k):
        _writeln('    case $pc:');
        _writeln('      if (${k ? "" : "!"}r[$a].isTruthy()) { pc = ${pc + 2}; } else { pc = $next; }');
        _writeln('      break;');

      case ABCInstruction(opcode: LualikeIrOpcode.testSet, a: final a, b: final b, k: final k):
        _writeln('    case $pc:');
        _writeln('      if (${k ? "" : "!"}r[$b].isTruthy()) { pc = ${pc + 2}; } else { r[$a] = r[$b]; pc = $next; }');
        _writeln('      break;');

      case AsJInstruction(opcode: LualikeIrOpcode.jmp, sJ: final sJ):
        _writeln('    case $pc: pc = ${pc + 1 + sJ}; break;');

      // For loop
      case AsBxInstruction(opcode: LualikeIrOpcode.forPrep, a: final a, sBx: final sBx):
        _writeln('    case $pc: {');
        _writeln('      r[${a + 3}] = r[${a + 2}];');
        _writeln('      r[${a + 2}] = r[${a + 1}];');
        _writeln('      final step = (r[${a + 2}].raw as num).toDouble();');
        _writeln('      final cond = step > 0');
        _writeln('          ? (r[$a].raw as num).toDouble() <= (r[${a + 1}].raw as num).toDouble()');
        _writeln('          : (r[$a].raw as num).toDouble() >= (r[${a + 1}].raw as num).toDouble();');
        _writeln('      pc = cond ? $next : ${pc + 1 + sBx};');
        _writeln('    } break;');

      case AsBxInstruction(opcode: LualikeIrOpcode.forLoop, a: final a, sBx: final sBx):
        _writeln('    case $pc: {');
        _writeln('      r[$a] = r[$a] + r[${a + 2}];');
        _writeln('      final step = (r[${a + 2}].raw as num).toDouble();');
        _writeln('      final cond = step > 0');
        _writeln('          ? (r[$a].raw as num).toDouble() <= (r[${a + 1}].raw as num).toDouble()');
        _writeln('          : (r[$a].raw as num).toDouble() >= (r[${a + 1}].raw as num).toDouble();');
        _writeln('      pc = cond ? ${pc + 1 + sBx} : $next;');
        _writeln('    } break;');

      // Tables
      case ABCInstruction(opcode: LualikeIrOpcode.getTable, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b][r[$c]];');
      case ABCInstruction(opcode: LualikeIrOpcode.setTable, a: final a, b: final b, c: final c):
        stmt('r[$a][r[$b]] = r[$c];');
      case ABCInstruction(opcode: LualikeIrOpcode.newTable, a: final a):
        stmt('r[$a] = _mkTable();');
      case ABCInstruction(opcode: LualikeIrOpcode.getField, a: final a, b: final b, c: final c):
        stmt('r[$a] = r[$b][${constExpr(c)}];');
      case ABCInstruction(opcode: LualikeIrOpcode.setField, a: final a, b: final b, c: final c):
        _writeln('    case $pc: r[$a][${constExpr(b)}] = r[$c]; pc = $next; break;');
      case ABCInstruction(opcode: LualikeIrOpcode.len, a: final a, b: final b):
        stmt('r[$a] = Value(r[$b].length);');
      // Upvalue access
      case ABCInstruction(opcode: LualikeIrOpcode.getUpval, a: final a, b: final b):
        _writeln('    case $pc: r[$a] = upvals[$b]; pc = $next; break;');
      case ABCInstruction(opcode: LualikeIrOpcode.setUpval, a: final a, b: final b, c: final c):
        _writeln('    case $pc: upvals[$b] = r[$c]; pc = $next; break;');

      // Global variable access
      case ABCInstruction(opcode: LualikeIrOpcode.getTabUp, a: final a, c: final c):
        _writeln('    case $pc: r[$a] = rt.globals.get(${strKey(c)}); pc = $next; break;');
      case ABCInstruction(opcode: LualikeIrOpcode.setTabUp, b: final b, c: final c):
        _writeln('    case $pc: rt.globals.define(${strKey(b)}, r[$c]); pc = $next; break;');

      // SETLIST (table constructor with array elements)
      case ABCInstruction(opcode: LualikeIrOpcode.setList, a: final a, b: final b, c: final c):
        _writeln('    case $pc: {');
        _writeln('      final idx0 = $c == 0 ? 1 : $c;');
        _writeln('      final n = $b == 0 ? r.length - ${a + 1} : $b;');
        _writeln('      for (var j = 0; j < n; j++) r[$a][Value(j + idx0)] = r[${a + 1} + j];');
        _writeln('      pc = $next;');
        _writeln('    } break;');

      // Calls
      case ABCInstruction(opcode: LualikeIrOpcode.call, a: final a, b: final b, c: final c):
        _writeln('    case $pc: {');
        _writeln('      final fn = r[$a];');
        _writeln('      final nargs = ${b == 0 ? "-1" : b - 1};');
        _writeln('      final callArgs = <Value>[];');
        _writeln('      for (var i = 0; i < (nargs < 0 ? r.length - ${a + 1} : nargs); i++) {');
        _writeln('        callArgs.add(r[${a + 1} + i]);');
        _writeln('      }');
        _writeln('      final result = await rt.callFunction(fn, callArgs);');
        _writeln('      r[$a] = result is Value ? result : Value(result);');
        _writeln('      pc = $next;');
        _writeln('    } break;');

      // Returns
      case ABCInstruction(opcode: LualikeIrOpcode.return1, a: final a):
        _writeln('    case $pc: return r[$a];');
      case LualikeIrInstruction(opcode: LualikeIrOpcode.return0):
        _writeln('    case $pc: return Value(null);');
      case ABCInstruction(opcode: LualikeIrOpcode.ret, a: final a, b: final b):
        _writeln('    case $pc: return r[$a];');

      case LualikeIrInstruction(opcode: LualikeIrOpcode.varArgPrep):
        _writeln('    case $pc: pc = $next; break;');

     // VARARG: copy varargs to registers
     case ABCInstruction(opcode: LualikeIrOpcode.varArg, a: final a, b: final b):
       _writeln('    case $pc: {');
       _writeln('      final n = $b == 0 ? varargs.length : ${b - 1};');
       _writeln('      for (var j = 0; j < n; j++) r[${a} + j] = j < varargs.length ? varargs[j] : Value(null);');
       _writeln('      pc = $next;');
       _writeln('    } break;');

     // GETVARG: get single vararg by index
     case ABCInstruction(opcode: LualikeIrOpcode.getVarArg, a: final a, c: final c):
       _writeln('    case $pc: {');
       _writeln('      final idx = $c <= 1 ? 0 : ${c - 1};');
       _writeln('      r[$a] = idx < varargs.length ? varargs[idx] : Value(null);');
       _writeln('      pc = $next;');
       _writeln('    } break;');
           // Generic for loop (TFOR*) — iterator protocol
      case AsBxInstruction(opcode: LualikeIrOpcode.tForPrep, a: final a, sBx: final sBx):
        _writeln('    case $pc: {');
        _writeln('      var tmp = r[${a + 2}];');
        _writeln('      r[${a + 2}] = r[${a + 3}];');
        _writeln('      r[${a + 3}] = tmp;');
        _writeln('      pc = ${pc + 1 + sBx};');
        _writeln('    } break;');

      case ABCInstruction(opcode: LualikeIrOpcode.tForCall, a: final a, c: final c):
        _writeln('    case $pc: {');
        _writeln('      final fn = r[$a];');
        _writeln('      final callArgs = <Value>[r[${a + 1}]];');
        _writeln('      final result = await rt.callFunction(fn, callArgs);');
        _writeln('      final results = result is Value ? [result] : (result as List).cast<Value>();');
        _writeln('      for (var j = 0; j < $c; j++) r[${a + 3} + j] = j < results.length ? results[j] : Value(null);');
        _writeln('      pc = $next;');
        _writeln('    } break;');

      case AsBxInstruction(opcode: LualikeIrOpcode.tForLoop, a: final a, sBx: final sBx):
        _writeln('    case $pc: {');
        _writeln('      if (r[${a + 3}] != null && r[${a + 3}].raw != null) { pc = ${pc + 1 + sBx}; } else { pc = $next; }');
        _writeln('    } break;');
// Close / tbc (no-op without closure support)
     case LualikeIrInstruction(opcode: LualikeIrOpcode.close):
     case LualikeIrInstruction(opcode: LualikeIrOpcode.tbc):
       _writeln('    case $pc: pc = $next; break;');

     // Concat: r[a] = r[b]..r[b+1].. ..r[c]
     case ABCInstruction(opcode: LualikeIrOpcode.concat, a: final a, b: final b, c: final c):
       _writeln('    case $pc: {');
       _writeln('      var s = r[$b].raw?.toString() ?? "";');
       _writeln('      for (var j = ${b + 1}; j <= $c; j++) s += r[j].raw?.toString() ?? "";');
       _writeln('      r[$a] = Value(s);');
       _writeln('      pc = $next;');
       _writeln('    } break;');

     // GETI / SETI: integer-key table access
     case ABCInstruction(opcode: LualikeIrOpcode.getI, a: final a, b: final b, c: final c):
       stmt('r[$a] = r[$b][Value($c)];');
     case ABCInstruction(opcode: LualikeIrOpcode.setI, a: final a, b: final b, c: final c):
       _writeln('    case $pc: r[$a][Value($b)] = r[$c]; pc = $next; break;');

     // SELF: method call sugar
     case ABCInstruction(opcode: LualikeIrOpcode.selfOp, a: final a, b: final b, c: final c):
       _writeln('    case $pc: {');
       _writeln('      r[$a] = r[$b];');
       _writeln('      r[${a + 1}] = r[$b][${constExpr(c)}];');
       _writeln('      pc = $next;');
       _writeln('    } break;');

     // TAILCALL: like CALL but return directly
     case ABCInstruction(opcode: LualikeIrOpcode.tailCall, a: final a, b: final b):
       _writeln('    case $pc: {');
       _writeln('      final fn = r[$a];');
       _writeln('      final nargs = ${b == 0 ? -1 : b - 1};');
       _writeln('      final callArgs = <Value>[];');
       _writeln('      for (var i = 0; i < (nargs < 0 ? r.length - ${a + 1} : nargs); i++) {');
       _writeln('        callArgs.add(r[${a + 1} + i]);');
       _writeln('      }');
       _writeln('      final result = await rt.callFunction(fn, callArgs); return result is Value ? result : Value(result);');
       _writeln('    } break;');
      default:
        unsupported();
    }
  }

  void _emitClosure(
    int a,
    int bx,
    LualikeIrPrototype proto,
    String fname,
    List<String> emitted,
    int pc,
  ) {
    final next = pc + 1;
    final child = proto.prototypes[bx];
    final childName = '${fname}_$bx';

    // Ensure the child function is emitted.
    _emitPrototype(child, childName, emitted);

    // Emit the closure creation.
    _writeln('    case $pc: {');

    // Capture outer upvalues into temps BEFORE the local shadows them.
    for (var i = 0; i < child.upvalueDescriptors.length; i++) {
      final desc = child.upvalueDescriptors[i];
      if (desc.inStack == 1) {
        _writeln('      final uv${i} = r[${desc.index}];');
      } else {
        _writeln('      final uv${i} = upvals[${desc.index}];');
      }
    }
    final uvRefs = <String>[];
    for (var i = 0; i < child.upvalueDescriptors.length; i++) {
      uvRefs.add('uv$i');
    }
    _writeln('      final capturedUpvals = <Value>[${uvRefs.join(', ')}];');

    // Create a Value wrapping a callable that invokes the child function.
      _writeln('      r[$a] = Value((List<Object?> callArgs) async => $childName(rt, callArgs.cast<Value>(), capturedUpvals, <Value>[]));');
    _writeln('      pc = $next;');
    _writeln('    } break;');
  }

  int _maxRegister(LualikeIrPrototype proto) {
    var m = -1;
    void check(int v) { if (v > m) m = v; }
    for (final inst in proto.instructions) {
      if (inst is ABCInstruction) {
        check(inst.a); check(inst.b); check(inst.c);
      }
      if (inst is AsBxInstruction) {
        check(inst.a);
      }
      if (inst is ABxInstruction) {
        check(inst.bx);
      }
    }
    // Ensure at least 1 register (for varArgPrep or empty functions).
    if (m < 0) return 0;
    return m;
  }

  String _es(String s) =>
    "'${s.replaceAll("'", "\\'").replaceAll('\n', '\\n').replaceAll('\r', '\\r').replaceAll('\t', '\\t')}'";
  String _dl(double v) {
    if (v.isNaN) return 'double.nan';
    if (v.isInfinite) return v.isNegative ? 'double.negativeInfinity' : 'double.infinity';
    return v.toString();
  }
  int _se(int value, int bits) =>
    (value << (32 - bits)) >> (32 - bits);

  void _writeln([String line = '']) => _buf.writeln(line);
}
