import 'instruction.dart';
import 'opcode.dart';
import 'prototype.dart';
import 'ssa.dart';
import 'ssa_type_analysis.dart';

/// Lowers a lualike IR prototype to LLVM IR using `lualike_rt` C runtime calls.
///
/// Function signature:
///   void @_lua_fn_N(ptr %L, ptr %r, i32 %nregs, ptr %upvals, i32 %nupvals,
///                   ptr %varargs, i32 %nvarargs, ptr %constants, i32 %nconstants)
///
/// Runtime must be linked separately (liblualike_rt.a).
class LualikeIrToLlvm {
  LualikeIrToLlvm({
    required this.prototype,
    required this.ssaFunction,
    required this.typeAnalysis,
    this.functionIndex = 0,
    this.targetTriple,
  });

  final LualikeIrPrototype prototype;
  final LualikeIrSsaFunction ssaFunction;
  final LualikeIrSsaTypeAnalysis typeAnalysis;
  final int functionIndex;
  final String? targetTriple;

  static const _valueSz = 16; // sizeof(lua_Value)

  final _buf = StringBuffer();
  int _unnamedCounter = 0;
  int _syntheticBlock = 1000000;
  bool _terminated = false;
  int _currentBlockIndex = 0;
  final _loopCheckLabels = <int, int>{};

  String generateModule() {
    _buf.clear();
    _unnamedCounter = 0;
    _emitHeader();
    // Emit extern globals for sub-function constants (Value = 16 bytes each)
    for (var i = 0; i < prototype.prototypes.length; i++) {
      final subNc = prototype.prototypes[i].constants.length;
      if (subNc > 0) {
        _writeln('@_lua_fn_const_${i + 1} = external global [${subNc * 2} x i64]');
      }
    }
    // Emit sub-functions first for forward references
    for (var i = 0; i < prototype.prototypes.length; i++) {
      final subProto = prototype.prototypes[i];
      final subSsa = LualikeIrSsaFunction.fromPrototype(subProto).simplifyTrivialPhis();
      final subTa = analyzeLualikeIrSsaTypes(subProto, subSsa);
      final subEmitter = LualikeIrToLlvm(
        prototype: subProto,
        ssaFunction: subSsa,
        typeAnalysis: subTa,
        functionIndex: i + 1,
        targetTriple: targetTriple,
      );
      subEmitter._emitFunction();
      _buf.write(subEmitter._buf.toString());
    }
    _emitFunction();
    return _buf.toString();
  }

  String generate() {
    _buf.clear();
    _unnamedCounter = 0;
    _emitFunction();
    return _buf.toString();
  }

  // --------------------------------------------------------------------------
  // Header
  // --------------------------------------------------------------------------

  void _emitHeader() {
    _writeln('; Generated by lualike LLVM lowering');
    if (targetTriple != null) _writeln('target triple = "$targetTriple"');
    _writeln('target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"');
    _writeln();
    _writeln('; lualike_rt runtime declarations');
    for (final d in _decls) _writeln(d);
    _writeln();
  }

  static const _decls = <String>[
    'declare i1 @lualike_istruthy(ptr)',
    'declare void @lualike_copy(ptr, ptr)',
    'declare void @lualike_pushnil(ptr)',
    'declare void @lualike_pushboolean(ptr, i8)',
    'declare void @lualike_pushnumber(ptr, double)',
    'declare void @lualike_pushinteger(ptr, i64)',
    'declare void @lualike_pushfunction(ptr, ptr)',
    'declare void @lualike_add(ptr, ptr, ptr, ptr)',
    'declare void @lualike_sub(ptr, ptr, ptr, ptr)',
    'declare void @lualike_mul(ptr, ptr, ptr, ptr)',
    'declare void @lualike_div(ptr, ptr, ptr, ptr)',
    'declare void @lualike_mod(ptr, ptr, ptr, ptr)',
    'declare void @lualike_pow(ptr, ptr, ptr, ptr)',
    'declare void @lualike_idiv(ptr, ptr, ptr, ptr)',
    'declare void @lualike_unm(ptr, ptr, ptr)',
    'declare void @lualike_band(ptr, ptr, ptr)',
    'declare void @lualike_bor(ptr, ptr, ptr)',
    'declare void @lualike_bxor(ptr, ptr, ptr)',
    'declare void @lualike_bnot(ptr, ptr, ptr)',
    'declare void @lualike_shl(ptr, ptr, ptr)',
    'declare void @lualike_shr(ptr, ptr, ptr)',
    'declare void @lualike_eq(ptr, ptr, ptr, ptr)',
    'declare void @lualike_lt(ptr, ptr, ptr, ptr)',
    'declare void @lualike_le(ptr, ptr, ptr, ptr)',
    'declare void @lualike_not(ptr, ptr)',
    'declare void @lualike_len(ptr, ptr, ptr)',
    'declare void @lualike_concat(ptr, ptr, ptr, ptr)',
    'declare void @lualike_newtable(ptr)',
    'declare void @lualike_gettable(ptr, ptr, ptr, ptr)',
    'declare void @lualike_settable(ptr, ptr, ptr, ptr)',
    'declare void @lualike_getfield(ptr, ptr, ptr, ptr)',
    'declare void @lualike_setfield(ptr, ptr, ptr, ptr)',
    'declare void @lualike_geti(ptr, ptr, ptr, i64)',
    'declare void @lualike_seti(ptr, ptr, i64, ptr)',
    'declare void @lualike_setlist(ptr, ptr, i32, i32, i32)',
    'declare void @lualike_getupval(ptr, ptr, i32)',
    'declare void @lualike_setupval(ptr, i32, ptr)',
    'declare void @lualike_newclosure(ptr, ptr, ptr, i32, ptr, ptr, i32)',
    'declare void @lualike_call(ptr, ptr, ptr, ptr, i32)',
    'declare void @lualike_tailcall(ptr, ptr, ptr, ptr, i32)',
    'declare void @lualike_gettabup(ptr, ptr, ptr, i32)',
    'declare void @lualike_settabup(ptr, ptr, ptr, i32)',
    'declare void @lualike_error(ptr, ptr)',
    'declare i32 @lualike_forprep(ptr, i32)',
    'declare i32 @lualike_forloop(ptr, i32)',
    'declare i32 @lualike_tforloop(ptr, i32)',
  ];

  // --------------------------------------------------------------------------
  // Function
  // --------------------------------------------------------------------------

  void _emitFunction() {
    final name = _functionName();
    _writeln('define void @$name(');
    _writeln('  ptr %L, ptr %r, i32 %nregs,');
    _writeln('  ptr %upvals, i32 %nupvals,');
    _writeln('  ptr %varargs, i32 %nvarargs,');
    _writeln('  ptr %constants, i32 %nconstants');
    _writeln(') {');
    for (final sb in ssaFunction.blocks) _emitBlock(sb);
    _writeln('}');
  }

  // --------------------------------------------------------------------------
  // Block
  // --------------------------------------------------------------------------

  void _emitBlock(LualikeIrSsaBlock sb) {
    final b = sb.block;
    _writeln('${_label(b.index)}:');
    _terminated = false;
    _currentBlockIndex = b.index;
    for (final pc in b.instructionPcs) {
      if (_terminated) break;
      _emitOne(prototype.instructions[pc], pc);
    }
    if (!_terminated) {
      if (b.successors.isNotEmpty) {
        _writeln('  br label %${_label(b.successors.first)}');
      } else {
        _writeln('  ret void');
      }
    }
  }

  // --------------------------------------------------------------------------
  // Instruction dispatch
  // --------------------------------------------------------------------------

  void _emitOne(LualikeIrInstruction inst, int pc) {
    void R(int r) => _reg(r);
    void cpy(int d, int s) => _writeln('  call void @lualike_copy(ptr ${_reg(d)}, ptr ${_reg(s)})');
    void pushNil(int r) => _writeln('  call void @lualike_pushnil(ptr ${_reg(r)})');
    void pushBool(int r, bool v) => _writeln('  call void @lualike_pushboolean(ptr ${_reg(r)}, i8 ${v ? 1 : 0})');
    void pushInt(int r, int v) => _writeln('  call void @lualike_pushinteger(ptr ${_reg(r)}, i64 $v)');
    void pushNum(int r, double v) => _writeln('  call void @lualike_pushnumber(ptr ${_reg(r)}, double $v)');
    void call3(String fn, int a, int b, int c) =>
      _writeln('  call void @$fn(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr ${_reg(c)})');
    void call3c(String fn, int a, int b, int c) =>
      _writeln('  call void @$fn(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr ${_const(c)})');
    void call2(String fn, int a, int b) =>
      _writeln('  call void @$fn(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)})');
    void call2r(String fn, int a, int b) =>
      _writeln('  call void @$fn(ptr ${_reg(a)}, ptr ${_reg(b)})');
    void call3r(String fn, int a, int b, int c) =>
      _writeln('  call void @$fn(ptr ${_reg(a)}, ptr ${_reg(b)}, ptr ${_reg(c)})');
    void call3cr(String fn, int a, int b, int c) =>
      _writeln('  call void @$fn(ptr ${_reg(a)}, ptr ${_reg(b)}, ptr ${_const(c)})');
    void br(int target) {
      final idx = _findBlock(target);
      if (idx != null) { _writeln('  br label %${_label(idx)}'); _terminated = true; }
    }

    switch (inst) {
      // -- Loads --
      case ABCInstruction(opcode: LualikeIrOpcode.loadI, a: final a, b: final b):
        pushInt(a, _se(b, 8));
      case AsBxInstruction(opcode: LualikeIrOpcode.loadI, a: final a, sBx: final sBx):
        pushInt(a, sBx);
      case ABCInstruction(opcode: LualikeIrOpcode.loadF, a: final a, b: final b):
        pushNum(a, _se(b, 8).toDouble());
      case AsBxInstruction(opcode: LualikeIrOpcode.loadF, a: final a, sBx: final sBx):
        pushNum(a, sBx.toDouble());
      case ABCInstruction(opcode: LualikeIrOpcode.loadFalse, a: final a):
        pushBool(a, false);
      case ABCInstruction(opcode: LualikeIrOpcode.lFalseSkip, a: final a):
        pushBool(a, false);
      case ABCInstruction(opcode: LualikeIrOpcode.loadTrue, a: final a):
        pushBool(a, true);
      case ABCInstruction(opcode: LualikeIrOpcode.loadNil, a: final a, b: final b):
        for (var i = 0; i <= b; i++) pushNil(a + i);
      case ABxInstruction(opcode: LualikeIrOpcode.loadK, a: final a, bx: final bx):
        _writeln('  call void @lualike_copy(ptr ${_reg(a)}, ptr ${_const(bx)})');
      case LualikeIrInstruction(opcode: LualikeIrOpcode.extraArg):
        break;

      // -- Move --
      case ABCInstruction(opcode: LualikeIrOpcode.move, a: final a, b: final b):
        cpy(a, b);

      // -- Arithmetic (reg, reg) --
      case ABCInstruction(opcode: LualikeIrOpcode.add,  a: final a, b: final b, c: final c): call3('lualike_add', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.sub,  a: final a, b: final b, c: final c): call3('lualike_sub', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.mul,  a: final a, b: final b, c: final c): call3('lualike_mul', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.div,  a: final a, b: final b, c: final c): call3('lualike_div', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.mod,  a: final a, b: final b, c: final c): call3('lualike_mod', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.pow,  a: final a, b: final b, c: final c): call3('lualike_pow', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.idiv, a: final a, b: final b, c: final c): call3('lualike_idiv', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.unm,  a: final a, b: final b):              call2('lualike_unm', a, b);

      // -- Arithmetic (imm) — use stack temp to avoid overwriting r[b]
      case ABCInstruction(opcode: LualikeIrOpcode.addI, a: final a, b: final b, c: final c, k: final _): {
        final immReg = _next();
        _writeln('  $immReg = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $immReg, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_add(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr $immReg)');
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.subI, a: final a, b: final b, c: final c, k: final _): {
        final immReg = _next();
        _writeln('  $immReg = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $immReg, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_sub(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr $immReg)');
        break;
      }

      // -- Arithmetic (const) --
      case ABCInstruction(opcode: LualikeIrOpcode.addK,  a: final a, b: final b, c: final c): call3c('lualike_add', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.subK,  a: final a, b: final b, c: final c): call3c('lualike_sub', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.mulK,  a: final a, b: final b, c: final c): call3c('lualike_mul', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.divK,  a: final a, b: final b, c: final c): call3c('lualike_div', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.modK,  a: final a, b: final b, c: final c): call3c('lualike_mod', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.powK,  a: final a, b: final b, c: final c): call3c('lualike_pow', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.idivK, a: final a, b: final b, c: final c): call3c('lualike_idiv', a, b, c);

      // -- Bitwise (reg, reg) --
      case ABCInstruction(opcode: LualikeIrOpcode.band, a: final a, b: final b, c: final c): call3r('lualike_band', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.bor,  a: final a, b: final b, c: final c): call3r('lualike_bor', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.bxor, a: final a, b: final b, c: final c): call3r('lualike_bxor', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.bnot, a: final a, b: final b):              call2r('lualike_bnot', a, b);
      case ABCInstruction(opcode: LualikeIrOpcode.shl,  a: final a, b: final b, c: final c): call3r('lualike_shl', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.shr,  a: final a, b: final b, c: final c): call3r('lualike_shr', a, b, c);

      // -- Bitwise (const) --
      case ABCInstruction(opcode: LualikeIrOpcode.bandK, a: final a, b: final b, c: final c): call3cr('lualike_band', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.borK,  a: final a, b: final b, c: final c): call3cr('lualike_bor', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.bxorK, a: final a, b: final b, c: final c): call3cr('lualike_bxor', a, b, c);

      // -- Bitwise (imm) --
      case ABCInstruction(opcode: LualikeIrOpcode.shlI, a: final a, b: final b, c: final c):
        pushInt(a, c & 63); call2r('lualike_shl', a, b);
      case ABCInstruction(opcode: LualikeIrOpcode.shrI, a: final a, b: final b, c: final c):
        pushInt(a, c & 63); call2r('lualike_shr', a, b);

      // -- Metamethod dispatch --
      case ABCInstruction(opcode: LualikeIrOpcode.mmBin,  a: final a, b: final b, c: final c): call3('lualike_add', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.mmBinI, a: final a, b: final b, c: final c, k: final _): call3c('lualike_add', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.mmBinK, a: final a, b: final b, c: final c): call3c('lualike_add', a, b, c);

      // -- Comparisons --
      case ABCInstruction(opcode: LualikeIrOpcode.eq,  a: final a, b: final b, c: final c): call3('lualike_eq', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.lt,  a: final a, b: final b, c: final c): call3('lualike_lt', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.le,  a: final a, b: final b, c: final c): call3('lualike_le', a, b, c);
                  case ABCInstruction(opcode: LualikeIrOpcode.eqI, a: final a, b: final b, c: final c, k: final _): {
        final tmp = _next();
        _writeln('  $tmp = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $tmp, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_eq(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr $tmp)');
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.ltI, a: final a, b: final b, c: final c, k: final _): {
        final tmp = _next();
        _writeln('  $tmp = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $tmp, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_lt(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr $tmp)');
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.leI, a: final a, b: final b, c: final c, k: final _): {
        final tmp = _next();
        _writeln('  $tmp = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $tmp, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_le(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr $tmp)');
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.gtI, a: final a, b: final b, c: final c, k: final _): {
        // a > literal → literal < a
        final tmp = _next();
        _writeln('  $tmp = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $tmp, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_lt(ptr %L, ptr ${_reg(a)}, ptr $tmp, ptr ${_reg(b)})');
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.geI, a: final a, b: final b, c: final c, k: final _): {
        // a >= literal → literal <= a
        final tmp = _next();
        _writeln('  $tmp = alloca i64, i64 1');
        _writeln('  call void @lualike_pushinteger(ptr $tmp, i64 ${_se(c, 9)})');
        _writeln('  call void @lualike_le(ptr %L, ptr ${_reg(a)}, ptr $tmp, ptr ${_reg(b)})');
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.eqK, a: final a, b: final b, c: final c): call3c('lualike_eq', a, b, c);

      // -- Logical --
      case ABCInstruction(opcode: LualikeIrOpcode.notOp, a: final a, b: final b): call2('lualike_not', a, b);

      // -- Length --
      case ABCInstruction(opcode: LualikeIrOpcode.len, a: final a, b: final b): call2('lualike_len', a, b);

      // -- Concat --
      case ABCInstruction(opcode: LualikeIrOpcode.concat, a: final a, b: final b, c: final c):
        call3('lualike_concat', a, b, c);

      // -- Tables --
      case ABCInstruction(opcode: LualikeIrOpcode.newTable, a: final a):
        _writeln('  call void @lualike_newtable(ptr ${_reg(a)})');
      case ABCInstruction(opcode: LualikeIrOpcode.getTable, a: final a, b: final b, c: final c):
        call3('lualike_gettable', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.setTable, a: final a, b: final b, c: final c):
        call3('lualike_settable', a, b, c);
      case ABCInstruction(opcode: LualikeIrOpcode.getField, a: final a, b: final b, c: final c):
        _writeln('  call void @lualike_getfield(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, ptr ${_const(c)})');
      case ABCInstruction(opcode: LualikeIrOpcode.setField, a: final a, b: final b, c: final c):
        _writeln('  call void @lualike_setfield(ptr %L, ptr ${_reg(a)}, ptr ${_const(b)}, ptr ${_reg(c)})');
      case ABCInstruction(opcode: LualikeIrOpcode.getI, a: final a, b: final b, c: final c):
        _writeln('  call void @lualike_geti(ptr %L, ptr ${_reg(a)}, ptr ${_reg(b)}, i64 $c)');
      case ABCInstruction(opcode: LualikeIrOpcode.setI, a: final a, b: final b, c: final c):
        _writeln('  call void @lualike_seti(ptr %L, ptr ${_reg(a)}, i64 $b, ptr ${_reg(c)})');
      case ABCInstruction(opcode: LualikeIrOpcode.setList, a: final a, b: final b, c: final c):
        // Expand SETLIST into individual SETI calls
        if (b > 0) {
          final startIdx = (c - 1) * 50 + 1;
          for (var i = 0; i < b; i++) {
            _writeln('  call void @lualike_seti(ptr %L, ptr ${_reg(a)}, i64 ${startIdx + i}, ptr ${_reg(a + 1 + i)})');
          }
        }

      // -- Upvalues --
      case ABCInstruction(opcode: LualikeIrOpcode.getUpval, a: final a, b: final b):
        _writeln('  call void @lualike_getupval(ptr ${_reg(a)}, ptr %upvals, i32 $b)');
      case ABCInstruction(opcode: LualikeIrOpcode.setUpval, a: final a, b: final b, c: final c):
        _writeln('  call void @lualike_setupval(ptr %upvals, i32 $b, ptr ${_reg(c)})');

      // -- Globals --
      case ABCInstruction(opcode: LualikeIrOpcode.getTabUp, a: final a, c: final c):
        _writeln('  call void @lualike_gettabup(ptr ${_reg(a)}, ptr %upvals, ptr %constants, i32 $c)');
      case ABCInstruction(opcode: LualikeIrOpcode.setTabUp, a: final a, c: final c):
        _writeln('  call void @lualike_settabup(ptr %upvals, ptr %constants, ptr ${_reg(a)}, i32 $c)');

      // -- Closure --
      case ABxInstruction(opcode: LualikeIrOpcode.closure, a: final a, bx: final bx):
        // bx indexes into the CURRENT function's prototypes, not the root's
        // We just pass null for constants and 0 — the Zig wrapper will
        // resolve the actual constants via the function index.
        _writeln('  call void @lualike_newclosure(ptr ${_reg(a)}, ptr @_lua_fn_${bx + 1}, ptr %upvals, i32 %nupvals, ptr null, ptr null, i32 0)');

      // -- Self --
      case ABCInstruction(opcode: LualikeIrOpcode.selfOp, a: final a, b: final b, c: final c):
        cpy(a, b);
        _writeln('  call void @lualike_getfield(ptr %L, ptr ${_reg(a + 1)}, ptr ${_reg(b)}, ptr ${_const(c)})');

      // -- Calls --
      case ABCInstruction(opcode: LualikeIrOpcode.call, a: final a, b: final b, c: final _):
        _writeln('  call void @lualike_call(ptr %L, ptr ${_reg(a)}, ptr ${_reg(a)}, ptr ${_reg(a + 1)}, i32 ${b == 0 ? -1 : b - 1})');
      case ABCInstruction(opcode: LualikeIrOpcode.tailCall, a: final a, b: final b):
        _writeln('  call void @lualike_tailcall(ptr %L, ptr ${_reg(a)}, ptr ${_reg(a)}, ptr ${_reg(a + 1)}, i32 ${b == 0 ? -1 : b - 1})');

      // -- Returns --
      case ABCInstruction(opcode: LualikeIrOpcode.return1, a: final a):
        cpy(0, a); _writeln('  ret void'); _terminated = true;
      case LualikeIrInstruction(opcode: LualikeIrOpcode.return0):
        _writeln('  call void @lualike_pushnil(ptr %r)'); _writeln('  ret void'); _terminated = true;
      case ABCInstruction(opcode: LualikeIrOpcode.ret, a: final a, b: final b):
        if (b > 1) cpy(0, a);
        else _writeln('  call void @lualike_pushnil(ptr %r)');
        _writeln('  ret void'); _terminated = true;

      // -- Varargs --
      case LualikeIrInstruction(opcode: LualikeIrOpcode.varArgPrep):
        break;
      case ABCInstruction(opcode: LualikeIrOpcode.varArg, a: final a, b: final _):
        cpy(a, 0);
      case ABCInstruction(opcode: LualikeIrOpcode.getVarArg, a: final a, c: final c):
        _writeln('  call void @lualike_getupval(ptr ${_reg(a)}, ptr %varargs, i32 ${c <= 1 ? 0 : c - 1})');

      // -- For loops --
      // FORPREP: pre-decrement and branch to synthetic FORLOOP check block
      case AsBxInstruction(opcode: LualikeIrOpcode.forPrep, a: final a, sBx: final sBx): {
        _writeln('  call i32 @lualike_forprep(ptr %r, i32 $a)');
        final bodyBlock = _findBlock(pc + 1);          // block containing the body
        final exitBlock = _findBlock(pc + 1 + sBx + 1); // block after FORLOOP
        if (bodyBlock >= 0) {
          final checkLabel = _syntheticBlock++;
          _loopCheckLabels[bodyBlock] = checkLabel;
          final exitLabel = exitBlock >= 0 ? _label(exitBlock) : 'b${_syntheticBlock++}';
          final cont = _next(); final cond = _next();
          _writeln('  br label %b_check_$checkLabel');
          _terminated = true;
          _writeln('b_check_$checkLabel:');
          _writeln('  $cont = call i32 @lualike_forloop(ptr %r, i32 $a)');
          _writeln('  $cond = icmp ne i32 $cont, 0');
          _writeln('  br i1 $cond, label %${_label(bodyBlock)}, label %$exitLabel');
        }
        break;
      }
      
      case AsBxInstruction(opcode: LualikeIrOpcode.forLoop, a: final a, sBx: final sBx): {
        final checkLabel = _loopCheckLabels[_currentBlockIndex];
        if (checkLabel != null) {
          _writeln('  br label %b_check_$checkLabel');
          _terminated = true;
        }
        break;
      }

      // -- Generic for --
      case AsBxInstruction(opcode: LualikeIrOpcode.tForPrep, a: final a, sBx: final sBx): {
        // Copy initial key from r[a+2] to r[a+3]
        _writeln('  call void @lualike_copy(ptr ${_reg(a + 3)}, ptr ${_reg(a + 2)})');
        final bodyBlock = _findBlock(pc + 1);
        if (bodyBlock >= 0) {
          final exitBlock = _findBlock(pc + 1 + sBx + 1);
          final checkLabel = _syntheticBlock++;
          _loopCheckLabels[bodyBlock] = checkLabel;
          // First call to iterator (entry from b0)
          _writeln('  call void @lualike_call(ptr %L, ptr ${_reg(a + 3)}, ptr ${_reg(a)}, ptr ${_reg(a + 1)}, i32 2)');
          _writeln('  call void @lualike_copy(ptr ${_reg(a + 2)}, ptr ${_reg(a + 3)})');
          _writeln('  br label %b_tcheck_$checkLabel');
          _terminated = true;
          _writeln('b_tcheck_$checkLabel:');
          // Check result only (no iterator call - tForCall does that)
          final cont = _next(); final cond = _next();
          _writeln('  $cont = call i32 @lualike_tforloop(ptr %r, i32 $a)');
          _writeln('  $cond = icmp ne i32 $cont, 0');
          final bodySsa = ssaFunction.blocks.firstWhere(
            (b) => b.block.index == bodyBlock,
            orElse: () => ssaFunction.blocks.first,
          );
          var exitLabel = bodySsa.block.successors.length > 1 &&
                  bodySsa.block.successors[0] == bodyBlock
              ? _label(bodySsa.block.successors[1])
              : (bodySsa.block.successors.isNotEmpty
                  ? _label(bodySsa.block.successors.first)
                  : 'b${_syntheticBlock++}');
          _writeln('  br i1 $cond, label %${_label(bodyBlock)}, label %$exitLabel');
        }
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.tForCall, a: final a, c: final _): {
        // tForCall in the body: call iterator and copy result to r[a+2]
        final checkLabel = _loopCheckLabels[_currentBlockIndex];
        if (checkLabel != null) {
          _writeln('  call void @lualike_call(ptr %L, ptr ${_reg(a + 3)}, ptr ${_reg(a)}, ptr ${_reg(a + 1)}, i32 2)');
          _writeln('  call void @lualike_copy(ptr ${_reg(a + 2)}, ptr ${_reg(a + 3)})');
          _writeln('  br label %b_tcheck_$checkLabel');
          _terminated = true;
        }
        break;
      }
      case AsBxInstruction(opcode: LualikeIrOpcode.tForLoop, a: final a, sBx: final sBx): {
        final checkLabel = _loopCheckLabels[_currentBlockIndex];
        if (checkLabel != null) {
          _writeln('  br label %b_tcheck_$checkLabel');
          _terminated = true;
        }
        break;
      }

      // -- Close / TBC --
      case LualikeIrInstruction(opcode: LualikeIrOpcode.close):
      case LualikeIrInstruction(opcode: LualikeIrOpcode.tbc):
        break;

      // -- Test / TestSet / Jmp --
      case ABCInstruction(opcode: LualikeIrOpcode.test, a: final a, k: final k): {
        // TEST R(A) k — skip next if R(A) is truthy XOR k
        // In Lua: if k==0: skip next if R(A) is false. if k==1: skip next if R(A) is true.
        // LLVM successors[0] = fallthrough (skip), successors[1] = taken (no skip)
        final sb = ssaFunction.blocks[_currentBlockIndex];
        if (sb.block.successors.length >= 2) {
          final cond = _next();
          _writeln('  $cond = call i1 @lualike_istruthy(ptr ${_reg(a)})');
          if (k) {
            // k=1: skip if truthy → when truthy go to fallthrough, when falsy go to taken
            _writeln('  br i1 $cond, label %${_label(sb.block.successors[0])}, label %${_label(sb.block.successors[1])}');
          } else {
            // k=0: skip if falsy → when truthy go to taken, when falsy go to fallthrough
            _writeln('  br i1 $cond, label %${_label(sb.block.successors[1])}, label %${_label(sb.block.successors[0])}');
          }
          _terminated = true;
        }
        break;
      }
      case ABCInstruction(opcode: LualikeIrOpcode.testSet, a: final a, b: final b, k: final _):
        cpy(a, b);
      case AsJInstruction(opcode: LualikeIrOpcode.jmp, sJ: final sJ):
        br(pc + 1 + sJ);

      // -- Unsupported --
      default:
        _unsupported(inst);
    }
  }

  void _unsupported(LualikeIrInstruction inst) {
    _writeln('  call void @lualike_error(ptr %L, ptr null)');
    _writeln('  ret void');
    _terminated = true;
  }

  // --------------------------------------------------------------------------
  // Helpers
  // --------------------------------------------------------------------------

  String _functionName() => '_lua_fn_$functionIndex';
  String _label(int i) => 'b$i';
  String _next() => '%t${_unnamedCounter++}';

  String _reg(int r) {
    final p = _next();
    _writeln('  $p = getelementptr i8, ptr %r, i32 ${r * _valueSz}');
    return p;
  }

  String _const(int i) {
    final p = _next();
    _writeln('  $p = getelementptr i8, ptr %constants, i32 ${i * _valueSz}');
    return p;
  }

  int _findBlock(int pc) {
    for (final sb in ssaFunction.blocks) {
      if (sb.block.startPc <= pc && pc < sb.block.endPc) return sb.block.index;
    }
    return -1;
  }

  int _se(int v, int bits) => (v << (32 - bits)) >> (32 - bits);

  void _writeln([String l = '']) => _buf.writeln(l);
}
