import 'instruction.dart';
import 'opcode.dart';
import 'prototype.dart';
import 'ssa.dart';
import 'ssa_type_analysis.dart';

/// Lowers a lualike IR prototype (function) to LLVM IR assembly text.
///
/// The lowering requires an [LualikeIrSsaFunction] and its type analysis.
/// Any instruction that operates on `unknown`-typed values or is a runtime-only
/// opcode emits a call to `@lualike_abort` followed by `unreachable`.
///
/// ## Supported subset
///
/// | Lua construct | IR opcodes | LLVM lowering |
/// |---|---|---|
/// | Numbers | loadI, loadF, loadK (number/int), add/sub/mul/div/mod/pow/idiv, unm, addI/subI, addK/subK/*K | `double` arithmetic |
/// | Bitwise | band/bor/bxor/shl/shr/bnot | `i64` ops (via fptosi/.../sitofp) |
/// | Booleans | loadFalse, loadTrue, notOp, comparisons | `i8` + `zext`/`trunc` |
/// | Nil | loadNil | `i8 0` |
/// | Comparison | eq/lt/le, eqI/ltI/leI/gtI/geI, eqK | `fcmp` + `zext i1 to i8` |
/// | Control flow | jmp | `br label %target` |
/// | Loops | forPrep, forLoop | `br` + `phi double` + `fcmp` |
/// | Branching | test, testSet | `br i1` / `select` / copy |
/// | Move | move | no-op alias |
/// | Returns | return1, return0, ret(1) | `ret double` / `ret void` |
///
/// ## Unsupported (abort at compile time)
///
/// Tables, closures, upvalues, varargs, function calls, tail calls,
/// string concat, tfor*, close, self, checkGlobal.
class LualikeIrToLlvm {
  LualikeIrToLlvm({
    required this.prototype,
    required this.ssaFunction,
    required this.typeAnalysis,
    this.functionIndex = 0,
    this.targetTriple,
  });

  final LualikeIrPrototype prototype;
  final LualikeIrSsaFunction ssaFunction;
  final LualikeIrSsaTypeAnalysis typeAnalysis;
  final int functionIndex;
  final String? targetTriple;

  final _buffer = StringBuffer();
  int _blockCounter = 0;
  int _unnamedCounter = 0;

  /// Generates LLVM IR assembly text for the function.
  String generate() {
    _buffer.clear();
    _unnamedCounter = 0;

    _emitFunction();
    return _buffer.toString();
  }

  // ---------------------------------------------------------------------------
  // Module-level helpers
  // ---------------------------------------------------------------------------

  /// Generates a complete LLVM module containing the compiled function plus
  /// any helper declarations.
  String generateModule() {
    _buffer.clear();
    _unnamedCounter = 0;

    _emitHeader();
    _emitFunction();
    return _buffer.toString();
  }

  void _emitHeader() {
    _writeln('; Module generated by lualike LLVM lowering');
    if (targetTriple != null) {
      _writeln('target triple = "$targetTriple"');
    }
    _writeln(
      'target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"',
    );
    _writeln();

    // Declare C library functions we might need.
    _writeln('declare double @llvm.fabs.f64(double)');
    _writeln('declare double @pow(double, double)');
    _writeln('declare double @fmod(double, double)');
    _writeln('declare double @floor(double)');
    _writeln();

    // Abort function for unsupported runtime paths.
    _writeln('declare void @lualike_abort(i8*) noreturn');
    _writeln();
  }

  // ---------------------------------------------------------------------------
  // Function generation
  // ---------------------------------------------------------------------------

  void _emitFunction() {
    final hasClosures = prototype.prototypes.isNotEmpty;

    // Synthetic block labels start after real SSA block labels.
    _blockCounter = ssaFunction.blocks.length;

    // Check whether runtime features are actually *used*, not just declared.
    // The main chunk always has `isVararg = true` and an `_ENV` upvalue even
    // when the code references neither.
    final hasUsedUpvalues = prototype.instructions.any((inst) {
      final op = inst.opcode;
      return op == LualikeIrOpcode.getUpval ||
          op == LualikeIrOpcode.setUpval ||
          op == LualikeIrOpcode.getTabUp ||
          op == LualikeIrOpcode.setTabUp;
    });
    // `VARARGPREP` is setup-only and safe to skip; actual vararg access
    // is via `getVarArg` / `varArg`.
    final hasUsedVararg = prototype.instructions.any((inst) {
      final op = inst.opcode;
      return op == LualikeIrOpcode.getVarArg || op == LualikeIrOpcode.varArg;
    });
    if (hasUsedUpvalues || hasClosures || hasUsedVararg) {
      _writeln(
        '; SKIPPED: function uses upvalues/closures/varargs (uncompilable)',
      );
      _writeln();
      return;
    }

    // Determine function signature.
    final funcName = _functionName();
    final paramCount = prototype.paramCount;

    // Build parameter list — all `double` by convention.
    final params = <String>[];
    for (var i = 0; i < paramCount; i++) {
      params.add('double %p$i');
    }

    final returnType = _functionReturnType();

    _writeln('define $returnType @$funcName(${params.join(', ')}) {');

    // Emit all SSA blocks.
    for (final block in ssaFunction.blocks) {
      _emitBlock(block);
    }

    _writeln('}');
    _writeln();
  }

  String _functionName() => '_lua_fn_$functionIndex';

  String _functionReturnType() {
    // Examine all blocks for return instructions.
    for (final block in ssaFunction.blocks) {
      for (final pc in block.block.instructionPcs) {
        final inst = prototype.instructions[pc];
        if (inst.opcode == LualikeIrOpcode.return1 ||
            (inst.opcode == LualikeIrOpcode.ret &&
                inst is ABCInstruction &&
                inst.b == 2)) {
          return 'double';
        }
      }
    }
    return 'void';
  }

  // ---------------------------------------------------------------------------
  // Block generation
  // ---------------------------------------------------------------------------

  void _emitBlock(LualikeIrSsaBlock ssaBlock) {
    final block = ssaBlock.block;
    final blockLabel = _blockLabel(block.index);

    _writeln('$blockLabel:');

    _currentSsaBlock = block.index;
    _aborted = false;
    _terminated = false;
    _testCondition = null;

    // Build a register → current SSA value map starting from entry values.
    final currentValues = Map<int, LualikeIrSsaValue>.from(
      ssaBlock.entryValues,
    );

    // Emit phi nodes.
    for (final phi in ssaBlock.phis) {
      _emitPhi(phi, currentValues);
      currentValues[phi.targetRegister] = phi.value;
    }

    // Emit instructions in order.  After an abort, skip remaining
    // instructions — the block is already terminated by `unreachable`.
    for (final pc in block.instructionPcs) {
      if (_aborted) break;
      _currentPc = pc;
      final inst = prototype.instructions[pc];
      _emitInstruction(inst, pc, currentValues);
    }

    // If the block has successors but no terminator was emitted yet, add
    // a fall-through branch to the first successor.
    if (!_terminated && block.successors.isNotEmpty) {
      final succ = block.successors.first;
      _writeln('  br label %${_blockLabel(succ)}');
      _terminated = true;
    }

    // If we aborted but the function return type expects a ret, emit one
    // in a new unreachable block so the IR is well-formed.
    if (_aborted && _functionReturnType() == 'double') {
      final retLabel = _nextBlockLabel();
      _writeln('$retLabel:');
      _writeln('  ret double 0.0');
      _terminated = true;
    } else if (_aborted) {
      final retLabel = _nextBlockLabel();
      _writeln('$retLabel:');
      _writeln('  ret void');
      _terminated = true;
    }
  }

  // ---------------------------------------------------------------------------
  // Phi emission
  // ---------------------------------------------------------------------------

  void _emitPhi(
    LualikeIrPhi phi,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final value = phi.value;
    final llvmType = _llvmType(value);
    if (llvmType == null) {
      _writeln('  ; PHI skipped: unknown type for r${value.register}');
      return;
    }

    final incomingList = <String>[];
    for (final entry in phi.incomingByPredecessor.entries) {
      final predBlock = entry.key;
      final incomingValue = entry.value;
      final predLabel = _blockLabel(predBlock);
      incomingList.add(
        '[${_ssaRef(incomingValue)}, %$predLabel]',
      );
    }

    if (incomingList.isEmpty) {
      _writeln('  ; PHI r${value.register} has no incoming edges');
      return;
    }

    _writeln(
      '  ${_ssaRef(value)} = phi $llvmType ${incomingList.join(', ')}',
    );
  }

  // ---------------------------------------------------------------------------
  // Instruction emission
  // ---------------------------------------------------------------------------

  void _emitInstruction(
    LualikeIrInstruction instruction,
    int pc,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    switch (instruction) {
      case ABCInstruction(opcode: LualikeIrOpcode.move, a: final a, b: final b):
        _emitMove(a, b, currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.loadI, a: final a, b: final b):
        _emitLoadI(a, b, currentValues);

      case AsBxInstruction(opcode: LualikeIrOpcode.loadI, a: final a, sBx: final sBx):
        _emitLoadIFromSbx(a, sBx, currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.loadF, a: final a, b: final b):
        _emitLoadF(a, b, currentValues);

      case AsBxInstruction(opcode: LualikeIrOpcode.loadF, a: final a, sBx: final sBx):
        _emitLoadFFromSbx(a, sBx, currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.loadFalse, a: final a):
        _emitLoadConst(a, 'i8 0', currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.lFalseSkip, a: final a):
        _emitLoadConst(a, 'i8 0', currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.loadTrue, a: final a):
        _emitLoadConst(a, 'i8 1', currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.loadNil, a: final a, b: final b):
        _emitLoadNil(a, b, currentValues);

      case ABxInstruction(opcode: LualikeIrOpcode.loadK, a: final a, bx: final bx):
        _emitLoadK(a, bx, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.add,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBinary(a, b, c, 'fadd', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.sub,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBinary(a, b, c, 'fsub', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.mul,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBinary(a, b, c, 'fmul', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.div,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBinary(a, b, c, 'fdiv', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.mod,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitFmod(a, b, c, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.pow,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitPow(a, b, c, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.idiv,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitFloorDiv(a, b, c, currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.unm, a: final a, b: final b):
        _emitUnary(a, b, 'fneg', currentValues);

      // Immediate variants.
      case ABCInstruction(
        opcode: LualikeIrOpcode.addI ,
a: final aI,
        b: final bI,
        c: final cI,
      ):
        _emitBinaryImmediate(aI, bI, cI, 'fadd', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.subI ,
a: final aIs,
        b: final bIs,
        c: final cIs,
      ):
        _emitBinaryImmediate(aIs, bIs, cIs, 'fsub', currentValues);

      // Constant-index variants.
      case ABCInstruction(
        opcode: LualikeIrOpcode.addK ,
a: final aAk,
        b: final bAk,
        c: final cAk,
      ):
        _emitBinaryConst(aAk, bAk, cAk, 'fadd', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.subK ,
a: final aSk,
        b: final bSk,
        c: final cSk,
      ):
        _emitBinaryConst(aSk, bSk, cSk, 'fsub', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.mulK ,
a: final aMk,
        b: final bMk,
        c: final cMk,
      ):
        _emitBinaryConst(aMk, bMk, cMk, 'fmul', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.divK ,
a: final aDk,
        b: final bDk,
        c: final cDk,
      ):
        _emitBinaryConst(aDk, bDk, cDk, 'fdiv', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.modK ,
a: final aMok,
        b: final bMok,
        c: final cMok,
      ):
        _emitFmodConst(aMok, bMok, cMok, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.powK ,
a: final aPk,
        b: final bPk,
        c: final cPk,
      ):
        _emitPowConst(aPk, bPk, cPk, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.idivK ,
a: final aIk,
        b: final bIk,
        c: final cIk,
      ):
        _emitFloorDivConst(aIk, bIk, cIk, currentValues);

      // Bitwise ops.
      case ABCInstruction(
        opcode: LualikeIrOpcode.band,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBitwise(a, b, c, 'and', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.bor,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBitwise(a, b, c, 'or', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.bxor,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitBitwise(a, b, c, 'xor', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.shl,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitShift(a, b, c, 'shl', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.shr,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitShift(a, b, c, 'lshr', currentValues);

      case ABCInstruction(opcode: LualikeIrOpcode.bnot, a: final a, b: final b):
        _emitBitwiseNot(a, b, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.shlI ,
a: final a,
        b: final b,
        c: final c,
      ):
        _emitShiftImm(a, b, c, 'shl', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.shrI ,
a: final a,
        b: final b,
        c: final c,
      ):
        _emitShiftImm(a, b, c, 'lshr', currentValues);

      // Bitwise constant-index variants.
      case ABCInstruction(
        opcode: LualikeIrOpcode.bandK ,
a: final aBk,
        b: final bBk,
        c: final cBk,
      ):
        _emitBitwiseConst(aBk, bBk, cBk, 'and', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.borK ,
a: final aBok,
        b: final bBok,
        c: final cBok,
      ):
        _emitBitwiseConst(aBok, bBok, cBok, 'or', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.bxorK ,
a: final aBxk,
        b: final bBxk,
        c: final cBxk,
      ):
        _emitBitwiseConst(aBxk, bBxk, cBxk, 'xor', currentValues);

      // Boolean ops.
      case ABCInstruction(opcode: LualikeIrOpcode.notOp, a: final a, b: final b):
        _emitNot(a, b, currentValues);

      // Comparisons.
      case ABCInstruction(
        opcode: LualikeIrOpcode.eq,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitCompare(a, b, c, 'oeq', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.lt,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitCompare(a, b, c, 'olt', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.le,
        a: final a,
        b: final b,
        c: final c,
      ):
        _emitCompare(a, b, c, 'ole', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.eqI ,
a: final aEi,
        b: final bEi,
        c: final cEi,
      ):
        _emitCompareImm(aEi, bEi, cEi, 'oeq', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.ltI ,
a: final aLi,
        b: final bLi,
        c: final cLi,
      ):
        _emitCompareImm(aLi, bLi, cLi, 'olt', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.leI ,
a: final aLei,
        b: final bLei,
        c: final cLei,
      ):
        _emitCompareImm(aLei, bLei, cLei, 'ole', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.gtI ,
a: final aGi,
        b: final bGi,
        c: final cGi,
      ):
        _emitCompareImm(aGi, bGi, cGi, 'ogt', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.geI ,
a: final aGei,
        b: final bGei,
        c: final cGei,
      ):
        _emitCompareImm(aGei, bGei, cGei, 'oge', currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.eqK ,
a: final aEqk,
        b: final bEqk,
        c: final cEqk,
      ):
        _emitCompareConst(aEqk, bEqk, cEqk, 'oeq', currentValues);

      // Branching and testing.
      case ABCInstruction(opcode: LualikeIrOpcode.test, a: final a, k: final k):
        _emitTest(a, k, currentValues);

      case ABCInstruction(
        opcode: LualikeIrOpcode.testSet ,
a: final aTs,
        b: final bTs,
        k: final kTs,
      ):
        _emitTestSet(aTs, bTs, kTs, currentValues);

      // Control flow.
      case AsJInstruction(opcode: LualikeIrOpcode.jmp, sJ: final sJ):
        _emitJmp(sJ, currentValues);

      case AsBxInstruction(
        opcode: LualikeIrOpcode.forPrep,
        a: final a,
        sBx: final sBx,
      ):
        _emitForPrep(a, sBx, currentValues);

      case AsBxInstruction(
        opcode: LualikeIrOpcode.forLoop,
        a: final a,
        sBx: final sBx,
      ):
        _emitForLoop(a, sBx, currentValues);

      // Vararg setup — no-op when varargs are never accessed.
      case LualikeIrInstruction(opcode: LualikeIrOpcode.varArgPrep):
        break;

      // Returns.
      case ABCInstruction(opcode: LualikeIrOpcode.return1, a: final a):
        _emitReturn1(a, currentValues);

      case LualikeIrInstruction(opcode: LualikeIrOpcode.return0):
        _emitReturn0();

      case ABCInstruction(opcode: LualikeIrOpcode.ret, a: final a, b: final b):
        _emitRet(a, b, currentValues);

      // Unsupported opcode.
      default:
        _emitAbort('unsupported opcode: ${instruction.opcode.name}');
    }
  }

  // ---------------------------------------------------------------------------
  // Load / Move
  // ---------------------------------------------------------------------------

  void _emitMove(int a, int b, Map<int, LualikeIrSsaValue> currentValues) {
    final bVal = currentValues[b];
    if (bVal == null) {
      _emitAbort('move from undefined register r$b');
      return;
    }

    final aVal = _findDefinedValue(a, currentValues);
    if (aVal == null) {
      _emitAbort('move target r$a has no SSA value');
      return;
    }

    final llvmType = _llvmType(aVal);
    if (llvmType == null) {
      _emitAbort('move to unknown type at r$a');
      return;
    }
    final bRef = _ssaRef(bVal);
    // LLVM IR is SSA — a copy must be a real instruction.
    // For doubles, use fadd with 0.0. For i8, use or with 0.
    if (llvmType == 'double') {
      _writeln('  ${_ssaRef(aVal)} = fadd double $bRef, 0.0');
    } else {
      _writeln('  ${_ssaRef(aVal)} = or i8 $bRef, 0');
    }
    currentValues[a] = aVal;
  }

  void _emitLoadI(int a, int imm, Map<int, LualikeIrSsaValue> currentValues) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final signed = _signExtend(imm, 8);
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i32 $signed to double');
    currentValues[a] = ssaVal;
  }

  void _emitLoadIFromSbx(
    int a,
    int sBx,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i32 $sBx to double');
    currentValues[a] = ssaVal;
  }

  void _emitLoadF(int a, int imm, Map<int, LualikeIrSsaValue> currentValues) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final signed = _signExtend(imm, 8);
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i32 $signed to double');
    currentValues[a] = ssaVal;
  }

  void _emitLoadFFromSbx(
    int a,
    int sBx,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i32 $sBx to double');
    currentValues[a] = ssaVal;
  }

  void _emitLoadConst(
    int a,
    String constant,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    // LLVM IR requires an actual instruction, not a bare constant.
    if (constant == 'i8 0') {
      _writeln('  ${_ssaRef(ssaVal)} = or i8 0, 0');
    } else if (constant == 'i8 1') {
      _writeln('  ${_ssaRef(ssaVal)} = or i8 0, 1');
    } else {
      _writeln('  ${_ssaRef(ssaVal)} = $constant');
    }
    currentValues[a] = ssaVal;
  }

  void _emitLoadNil(
    int a,
    int count,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    for (var offset = 0; offset <= count; offset++) {
      final reg = a + offset;
      final ssaVal = _findDefinedValue(reg, currentValues);
      if (ssaVal != null) {
        _writeln('  ${_ssaRef(ssaVal)} = or i8 0, 0');
        currentValues[reg] = ssaVal;
      }
    }
  }

  void _emitLoadK(
    int a,
    int constIndex,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;

    if (constIndex < 0 || constIndex >= prototype.constants.length) {
      _emitAbort('loadK: constant index $constIndex out of range');
      return;
    }

    final constant = prototype.constants[constIndex];
    switch (constant) {
      case IntegerConstant(value: final v):
        _writeln('  ${_ssaRef(ssaVal)} = sitofp i64 $v to double');
      case NumberConstant(value: final v):
        _writeln(
          '  ${_ssaRef(ssaVal)} = fadd double 0.0, ${_doubleLiteral(v)}',
        );
      case NilConstant():
        _writeln('  ${_ssaRef(ssaVal)} = or i8 0, 0');
      case BooleanConstant(value: final v):
        _writeln('  ${_ssaRef(ssaVal)} = or i8 0, ${v ? 1 : 0}');
      case ShortStringConstant() || LongStringConstant():
        _emitAbort('loadK: string constants not compilable');
    }
    currentValues[a] = ssaVal;
  }

  // ---------------------------------------------------------------------------
  // Binary arithmetic
  // ---------------------------------------------------------------------------

  void _emitBinary(
    int a,
    int b,
    int c,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);
    _writeln('  ${_ssaRef(ssaVal)} = $llvmOp double $bRef, $cRef');
    currentValues[a] = ssaVal;
  }

  void _emitBinaryImmediate(
    int a,
    int b,
    int c,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final imm = _signExtend(c, 9);
    _writeln('  ${_ssaRef(ssaVal)} = $llvmOp double $bRef, ${imm}.0');
    currentValues[a] = ssaVal;
  }

  void _emitBinaryConst(
    int a,
    int b,
    int constIndex,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final constVal = _constantDoubleValue(constIndex);
    if (constVal == null) {
      _emitAbort('binary with non-numeric constant');
      return;
    }
    _writeln(
      '  ${_ssaRef(ssaVal)} = $llvmOp double $bRef, ${_doubleLiteral(constVal)}',
    );
    currentValues[a] = ssaVal;
  }

  void _emitFmod(
    int a,
    int b,
    int c,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);
    _writeln(
      '  ${_ssaRef(ssaVal)} = call double @fmod(double $bRef, double $cRef)',
    );
    currentValues[a] = ssaVal;
  }

  void _emitPow(
    int a,
    int b,
    int c,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);
    _writeln(
      '  ${_ssaRef(ssaVal)} = call double @pow(double $bRef, double $cRef)',
    );
    currentValues[a] = ssaVal;
  }

  void _emitFloorDiv(
    int a,
    int b,
    int c,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);

    final id = _nextUnnamed();
    _writeln('  $id = fdiv double $bRef, $cRef');
    _writeln('  ${_ssaRef(ssaVal)} = call double @floor(double $id)');
    currentValues[a] = ssaVal;
  }

  void _emitFmodConst(
    int a,
    int b,
    int constIndex,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final constVal = _constantDoubleValue(constIndex);
    if (constVal == null) {
      _emitAbort('fmod with non-numeric constant');
      return;
    }
    _writeln(
      '  ${_ssaRef(ssaVal)} = call double @fmod(double $bRef, double ${_doubleLiteral(constVal)})',
    );
    currentValues[a] = ssaVal;
  }

  void _emitPowConst(
    int a,
    int b,
    int constIndex,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final constVal = _constantDoubleValue(constIndex);
    if (constVal == null) {
      _emitAbort('pow with non-numeric constant');
      return;
    }
    _writeln(
      '  ${_ssaRef(ssaVal)} = call double @pow(double $bRef, double ${_doubleLiteral(constVal)})',
    );
    currentValues[a] = ssaVal;
  }

  void _emitFloorDivConst(
    int a,
    int b,
    int constIndex,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final constVal = _constantDoubleValue(constIndex);
    if (constVal == null) {
      _emitAbort('idiv with non-numeric constant');
      return;
    }
    final id = _nextUnnamed();
    _writeln('  $id = fdiv double $bRef, ${_doubleLiteral(constVal)}');
    _writeln('  ${_ssaRef(ssaVal)} = call double @floor(double $id)');
    currentValues[a] = ssaVal;
  }

  // ---------------------------------------------------------------------------
  // Unary
  // ---------------------------------------------------------------------------

  void _emitUnary(
    int a,
    int b,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    _writeln('  ${_ssaRef(ssaVal)} = $llvmOp double $bRef');
    currentValues[a] = ssaVal;
  }

  // ---------------------------------------------------------------------------
  // Bitwise
  // ---------------------------------------------------------------------------

  void _emitBitwise(
    int a,
    int b,
    int c,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);
    final t1 = _nextUnnamed();
    final t2 = _nextUnnamed();
    final t3 = _nextUnnamed();
    _writeln('  $t1 = fptosi double $bRef to i64');
    _writeln('  $t2 = fptosi double $cRef to i64');
    _writeln('  $t3 = $llvmOp i64 $t1, $t2');
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i64 $t3 to double');
    currentValues[a] = ssaVal;
  }

  void _emitShift(
    int a,
    int b,
    int c,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);
    final t1 = _nextUnnamed();
    final t2 = _nextUnnamed();
    final t3 = _nextUnnamed();
    _writeln('  $t1 = fptosi double $bRef to i64');
    _writeln('  $t2 = fptosi double $cRef to i64');
    _writeln('  $t3 = $llvmOp i64 $t1, $t2');
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i64 $t3 to double');
    currentValues[a] = ssaVal;
  }

  void _emitBitwiseNot(
    int a,
    int b,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final t1 = _nextUnnamed();
    final t2 = _nextUnnamed();
    _writeln('  $t1 = fptosi double $bRef to i64');
    _writeln('  $t2 = xor i64 $t1, -1');
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i64 $t2 to double');
    currentValues[a] = ssaVal;
  }

  void _emitShiftImm(
    int a,
    int b,
    int c,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final t1 = _nextUnnamed();
    final t2 = _nextUnnamed();
    _writeln('  $t1 = fptosi double $bRef to i64');
    _writeln('  $t2 = $llvmOp i64 $t1, $c');
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i64 $t2 to double');
    currentValues[a] = ssaVal;
  }

  void _emitBitwiseConst(
    int a,
    int b,
    int constIndex,
    String llvmOp,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final constVal = _constantDoubleValue(constIndex);
    if (constVal == null) {
      _emitAbort('bitwise with non-numeric constant');
      return;
    }
    final t1 = _nextUnnamed();
    final t2 = _nextUnnamed();
    final t3 = _nextUnnamed();
    _writeln('  $t1 = fptosi double $bRef to i64');
    _writeln('  $t2 = fptosi double ${_doubleLiteral(constVal)} to i64');
    _writeln('  $t3 = $llvmOp i64 $t1, $t2');
    _writeln('  ${_ssaRef(ssaVal)} = sitofp i64 $t3 to double');
    currentValues[a] = ssaVal;
  }

  // ---------------------------------------------------------------------------
  // Boolean not
  // ---------------------------------------------------------------------------

  void _emitNot(
    int a,
    int b,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;

    final bVal = currentValues[b];
    if (bVal == null) {
      _emitAbort('not from undefined register r$b');
      return;
    }

    final bType = typeAnalysis.typeOf(bVal);
    switch (bType) {
      case LualikeIrSsaType.boolean:
      case LualikeIrSsaType.nil_:
        final bRef = _ssaRef(bVal);
        _writeln('  ${_ssaRef(ssaVal)} = xor i8 $bRef, 1');
      case LualikeIrSsaType.number:
        // In Lua, all numbers are truthy, so `not number` → false.
        _writeln('  ${_ssaRef(ssaVal)} = or i8 0, 0');
      case LualikeIrSsaType.unknown:
        _emitAbort('not on unknown-typed value');
    }
    currentValues[a] = ssaVal;
  }

  // ---------------------------------------------------------------------------
  // Comparisons
  // ---------------------------------------------------------------------------

  void _emitCompare(
    int a,
    int b,
    int c,
    String condition,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final cRef = _doubleRef(c, currentValues);
    final t = _nextUnnamed();
    _writeln('  $t = fcmp $condition double $bRef, $cRef');
    _writeln('  ${_ssaRef(ssaVal)} = zext i1 $t to i8');
    currentValues[a] = ssaVal;
  }

  void _emitCompareImm(
    int a,
    int b,
    int c,
    String condition,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final imm = _signExtend(c, 9);
    final t = _nextUnnamed();
    _writeln('  $t = fcmp $condition double $bRef, ${imm}.0');
    _writeln('  ${_ssaRef(ssaVal)} = zext i1 $t to i8');
    currentValues[a] = ssaVal;
  }

  void _emitCompareConst(
    int a,
    int b,
    int constIndex,
    String condition,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssaVal = _findDefinedValue(a, currentValues);
    if (ssaVal == null) return;
    final bRef = _doubleRef(b, currentValues);
    final constVal = _constantDoubleValue(constIndex);
    if (constVal == null) {
      _emitAbort('compare with non-numeric constant');
      return;
    }
    final t = _nextUnnamed();
    _writeln(
      '  $t = fcmp $condition double $bRef, ${_doubleLiteral(constVal)}',
    );
    _writeln('  ${_ssaRef(ssaVal)} = zext i1 $t to i8');
    currentValues[a] = ssaVal;
  }

  // ---------------------------------------------------------------------------
  // Test / TestSet
  // ---------------------------------------------------------------------------

  /// `TEST rA, k` — skip next instruction if truthiness(rA) == k.
  void _emitTest(
    int a,
    bool k,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final aVal = currentValues[a];
    if (aVal == null) {
      _emitAbort('test on undefined register r$a');
      return;
    }

    final aType = typeAnalysis.typeOf(aVal);
    switch (aType) {
      case LualikeIrSsaType.number:
        // Numbers are always truthy.
        if (k) {
          _emitAbort('test on always-truthy number with k=1 (skip always)');
        }
        // No-op: fall through.
        return;
      case LualikeIrSsaType.boolean:
      case LualikeIrSsaType.nil_:
        // Emit a truthiness flag without branching — the `jmp` instruction
        // uses this to emit br.
        final aRef = _ssaRef(aVal);
        final cond = _nextUnnamed();
        _writeln('  $cond = icmp ne i8 $aRef, 0');
        _testCondition = (cond: cond, k: k);
        return;
      case LualikeIrSsaType.unknown:
        _emitAbort('test on unknown-typed value');
    }
  }

  /// `TESTSET rA, rB, k` — if truthiness(rB) == k, skip next instruction;
  /// otherwise set rA = rB.
  void _emitTestSet(
    int a,
    int b,
    bool k,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final bVal = currentValues[b];
    if (bVal == null) {
      _emitAbort('testSet on undefined register r$b');
      return;
    }
    final aVal = _findDefinedValue(a, currentValues);
    if (aVal == null) return;

    final bType = typeAnalysis.typeOf(bVal);
    switch (bType) {
      case LualikeIrSsaType.number:
        if (k) {
          return;
        }
        _emitMove(a, b, currentValues);
        return;
      case LualikeIrSsaType.boolean:
      case LualikeIrSsaType.nil_:
        final bRef = _ssaRef(bVal);
        final cond = _nextUnnamed();
        _writeln('  $cond = icmp ne i8 $bRef, 0');
        _testCondition = (cond: cond, k: k);
        return;
      case LualikeIrSsaType.unknown:
        _emitAbort('testSet on unknown-typed value');
    }
  }

  // ---------------------------------------------------------------------------
  // Control flow
  // ---------------------------------------------------------------------------

  void _emitJmp(int offset, Map<int, LualikeIrSsaValue> currentValues) {
    final targetPc = _currentPc + 1 + offset;
    final block = ssaFunction.blocks[_currentSsaBlock];

    if (_testCondition != null) {
      // Conditional jump: test+jmp pair.
      final c = _testCondition!;
      final condVar = _nextUnnamed();
      // TEST k=0 skips JMP when falsy; k=1 skips when truthy.
      // Invert: JMP target is taken when the test skips.
      _writeln('  $condVar = xor i1 ${c.cond}, true');

      final jmpTarget = _blockIndexContainingPc(
        ssaFunction.blocks, targetPc,
      );
      if (jmpTarget == null) {
        _emitAbort('conditional jmp to unknown target');
        return;
      }
      // Fall-through is the other successor block.
      final fallthrough = block.block.successors
          .firstWhere((s) => s != jmpTarget, orElse: () => -1);
      if (fallthrough < 0) {
        _writeln('  br label %${_blockLabel(jmpTarget)}');
        _terminated = true;
      } else {
        _writeln(
          '  br i1 $condVar, label %${_blockLabel(jmpTarget)}, label %${_blockLabel(fallthrough)}',
        );
        _terminated = true;
      }
      _testCondition = null;
    } else {
      // Unconditional jump.
      final targetIndex = _blockIndexContainingPc(
        ssaFunction.blocks, targetPc,
      );
      if (targetIndex != null) {
        _writeln('  br label %${_blockLabel(targetIndex)}');
        _terminated = true;
      } else {
        _emitAbort('jmp to unknown target');
      }
    }
  }

  void _emitForPrep(
    int a,
    int sBx,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    // FORPREP defines new SSA versions for r[a]..r[a+3].
    // Emit copy instructions so these appear as LLVM values.
    for (var i = 0; i < 4; i++) {
      final reg = a + i;
      final ssaVal = _findDefinedValue(reg, currentValues);
      if (ssaVal == null) continue;
      // Version 0 values are never defined as LLVM instructions.
      // Emit with a zero constant when the source is uninitialized.
      final srcVal = currentValues[reg];
      if (srcVal != null && srcVal.version == 0) {
        _writeln('  ${_ssaRef(ssaVal)} = fadd double 0.0, 0.0');
      } else {
        final srcRef = _doubleRef(reg, currentValues);
        _writeln('  ${_ssaRef(ssaVal)} = fadd double $srcRef, 0.0');
      }
      currentValues[reg] = ssaVal;
    }

    final varRef = _doubleRef(a, currentValues);
    final limitRef = _doubleRef(a + 1, currentValues);
    final stepRef = _doubleRef(a + 2, currentValues);

    // Check if step > 0 and compare var with limit based on step direction.
    final t0 = _nextUnnamed();
    _writeln('  $t0 = fcmp ogt double $stepRef, 0.0');
    final t2 = _nextUnnamed();
    final t3 = _nextUnnamed();
    _writeln('  $t2 = fcmp ole double $varRef, $limitRef');
    _writeln('  $t3 = fcmp oge double $varRef, $limitRef');
    final cond = _nextUnnamed();
    _writeln('  $cond = select i1 $t0, i1 $t2, i1 $t3');

    final targetBlock = _blockIndexContainingPc(
      ssaFunction.blocks, _currentPc + 1 + sBx,
    );
    final skipBlock = _blockIndexContainingPc(
      ssaFunction.blocks, _currentPc + 1,
    );

    if (targetBlock != null && skipBlock != null) {
      if (targetBlock == skipBlock) {
        _writeln('  br label %${_blockLabel(targetBlock)}');
      } else {
        _writeln(
          '  br i1 $cond, label %${_blockLabel(targetBlock)}, label %${_blockLabel(skipBlock)}',
        );
      }
      _terminated = true;
    } else {
      _emitAbort('forPrep: unknown branch targets');
    }
  }

  void _emitForLoop(
    int a,
    int sBx,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    // FORLOOP defines r[a]..r[a+3].  Only r[a] is actually updated;
    // the rest are pass-through copies to satisfy the SSA versions.
    final varRef = _doubleRef(a, currentValues);
    final stepRef = _doubleRef(a + 2, currentValues);
    final limitRef = _doubleRef(a + 1, currentValues);

    // Update the loop variable: r[a] += r[a+2] (step).
    final newVar = _findDefinedValue(a, currentValues);
    if (newVar == null) {
      _emitAbort('forLoop: no SSA value for loop variable');
      return;
    }
    _writeln('  ${_ssaRef(newVar)} = fadd double $varRef, $stepRef');
    currentValues[a] = newVar;

    // Pass-through copies for r[a+1], r[a+2], r[a+3].
    for (var i = 1; i < 4; i++) {
      final reg = a + i;
      final ssaVal = _findDefinedValue(reg, currentValues);
      if (ssaVal == null) continue;
      final srcRef = _doubleRef(reg, currentValues);
      _writeln('  ${_ssaRef(ssaVal)} = fadd double $srcRef, 0.0');
      currentValues[reg] = ssaVal;
    }

    final t0 = _nextUnnamed();
    _writeln('  $t0 = fcmp ogt double $stepRef, 0.0');
    final t1 = _nextUnnamed();
    final t2 = _nextUnnamed();
    _writeln('  $t1 = fcmp ole double ${_ssaRef(newVar)}, $limitRef');
    _writeln('  $t2 = fcmp oge double ${_ssaRef(newVar)}, $limitRef');
    final cond = _nextUnnamed();
    _writeln('  $cond = select i1 $t0, i1 $t1, i1 $t2');

    final targetBlock = _blockIndexContainingPc(
      ssaFunction.blocks, _currentPc + 1 + sBx,
    );
    final exitBlock = _blockIndexContainingPc(
      ssaFunction.blocks, _currentPc + 1,
    );

    if (targetBlock != null && exitBlock != null) {
      if (targetBlock == exitBlock) {
        _writeln('  br label %${_blockLabel(targetBlock)}');
      } else {
        _writeln(
          '  br i1 $cond, label %${_blockLabel(targetBlock)}, label %${_blockLabel(exitBlock)}',
        );
      }
      _terminated = true;
    } else {
      _emitAbort('forLoop: unknown branch targets');
    }
  }

  // ---------------------------------------------------------------------------
  // Returns
  // ---------------------------------------------------------------------------

  void _emitReturn1(int a, Map<int, LualikeIrSsaValue> currentValues) {
    final aVal = currentValues[a];
    if (aVal == null) {
      _writeln('  ret double 0.0');
      _terminated = true;
      return;
    }
    final aType = typeAnalysis.typeOf(aVal);
    if (aType == LualikeIrSsaType.number) {
      final aRef = _doubleRef(a, currentValues);
      _writeln('  ret double $aRef');
      _terminated = true;
    } else {
      _writeln('  ret double 0.0');
      _terminated = true;
    }
  }

  void _emitReturn0() {
    _writeln('  ret void');
    _terminated = true;
  }

  void _emitRet(int a, int b, Map<int, LualikeIrSsaValue> currentValues) {
    if (b == 1) {
      _writeln('  ret void');
      _terminated = true;
    } else if (b == 2) {
      _emitReturn1(a, currentValues);
    } else {
      _emitAbort('multi-return not supported in compiled code');
    }
  }

  // ---------------------------------------------------------------------------
  // Abort
  // ---------------------------------------------------------------------------

  void _emitAbort(String message) {
    final msgId = _nextUnnamed();
    _writeln('  $msgId = alloca i8, i64 ${message.length + 1}');
    for (var i = 0; i < message.length; i++) {
      final gep = _nextUnnamed();
      _writeln('  $gep = getelementptr i8, i8* $msgId, i64 $i');
      _writeln(
        '  store i8 ${message.codeUnitAt(i)}, i8* $gep',
      );
    }
    final gepEnd = _nextUnnamed();
    _writeln('  $gepEnd = getelementptr i8, i8* $msgId, i64 ${message.length}');
    _writeln('  store i8 0, i8* $gepEnd');
    _writeln('  call void @lualike_abort(i8* $msgId)');
    _writeln('  unreachable');
    _terminated = true;
    _aborted = true;
  }

  /// Set to true when an abort has been emitted; subsequent instructions in
  /// the same block become dead code and must not produce output.
  bool _aborted = false;
  bool _terminated = false;

  /// When non-null, a condition computed by TEST/TESTSET that the next JMP
  /// should use for a conditional branch.
  ({String cond, bool k})? _testCondition;

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  // _currentPc is set each instruction in _emitBlock

  /// Finds the SSA value defined for register [reg] at instruction [pc] in
  /// the current block, or falls back to the entry value if not explicitly
  /// defined in this block.
  int _currentPc = 0;

  LualikeIrSsaValue? _findDefinedValue(
    int reg,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    // Walk the current block's defined values to find one whose pc matches.
    // This gives us the correct SSA version for instructions that redefine
    // a register (e.g. LOADI then ADDI to the same register).
    final block = ssaFunction.blocks[_currentSsaBlock];
    for (final value in block.definedValues) {
      if (value.register == reg && value.definingPc == _currentPc) {
        return value;
      }
    }
    return currentValues[reg];
  }

  int _currentSsaBlock = 0;

  /// Returns the LLVM IR type string for an SSA value.
  String? _llvmType(LualikeIrSsaValue value) {
    return switch (typeAnalysis.typeOf(value)) {
      LualikeIrSsaType.nil_ || LualikeIrSsaType.boolean => 'i8',
      LualikeIrSsaType.number => 'double',
      LualikeIrSsaType.unknown => null,
    };
  }

  /// Returns the LLVM IR reference string for [value].
  String _llvmRef(
    LualikeIrSsaValue value,
    Map<int, LualikeIrSsaValue> currentValues,
  ) {
    final ssType = _llvmType(value);
    if (ssType == null) return 'double 0.0';
    return '$ssType ${_ssaRef(value)}';
  }

  /// Returns a value reference for register [reg] (without type prefix).
  String _doubleRef(int reg, Map<int, LualikeIrSsaValue> currentValues) {
    final value = currentValues[reg];
    if (value == null) return '0.0';
    return _ssaRef(value);
  }

  /// Returns the SSA reference string (e.g. `%r5_v12`) for an SSA value.
  String _ssaRef(LualikeIrSsaValue value) {
    return '%r${value.register}_v${value.version}';
  }

  String _blockLabel(int index) => 'b$index';

  String _nextBlockLabel() {
    final label = 'b${_blockCounter}';
    _blockCounter++;
    return label;
  }

  String _nextUnnamed() => '%t${_unnamedCounter++}';

  int? _blockIndexContainingPc(
    List<LualikeIrSsaBlock> blocks,
    int pc,
  ) {
    for (final block in blocks) {
      if (block.block.startPc <= pc && pc < block.block.endPc) {
        return block.block.index;
      }
    }
    return null;
  }

  String _doubleLiteral(double value) {
    // Use LLVM hex float format via raw bit representation.
    if (value.isNaN) return '0x7FF8000000000000';
    if (value.isInfinite) {
      return value.isNegative
          ? '0xFFF0000000000000'
          : '0x7FF0000000000000';
    }
    // Dart's toString produces a round-trippable short representation.
    return value.toString();
  }

  int _signExtend(int value, int bits) {
    final shift = 32 - bits;
    return (value << shift) >> shift;
  }

  double? _constantDoubleValue(int index) {
    if (index < 0 || index >= prototype.constants.length) return null;
    return switch (prototype.constants[index]) {
      NumberConstant(value: final v) => v,
      IntegerConstant(value: final v) => v.toDouble(),
      _ => null,
    };
  }

  void _writeln([String line = '']) {
    _buffer.writeln(line);
  }
}
