targets:
  $default:
    builders:
      lualike|table_schema:
        enabled: true
        generate_for:
          - "lib/**_schema.dart"
          - "lib/**_plugin_info.dart"
          - "lib/**/*_table.dart"
