// GENERATED CODE — DO NOT MODIFY BY HAND.
// Generated by TableSchemaBuilder.

import 'package:lualike/library_builder.dart' show FieldDoc, TableDoc;

final settingsEntry = TableDoc(
  name: 'SettingsEntry',
  description: 'A user-facing configuration option.',
  fields: [
    FieldDoc(
      key: 'key',
      type: 'string',
      description: 'Unique setting key used in code.',
      required: true,
    ),
    FieldDoc(
      key: 'label',
      type: 'string',
      description: 'Human-readable label shown in UI.',
      required: true,
    ),
    FieldDoc(
      key: 'kind',
      type: '"boolean" | "string" | "slider" | "select"',
      description: 'Controls the UI widget type and value coercion.',
      required: true,
    ),
    FieldDoc(
      key: 'hint',
      type: 'String?',
      description: 'Short help text displayed below the control.',
      required: false,
    ),
    FieldDoc(
      key: 'required',
      type: 'boolean',
      description: 'Whether the user must provide a value.',
      required: false,
    ),
    FieldDoc(
      key: 'defaultValue',
      type: 'String?',
      description: 'Fallback value when the user has not set one.',
      required: false,
    ),
    FieldDoc(
      key: 'group',
      type: 'String?',
      description: 'UI group for organising related settings.',
      required: false,
    ),
    FieldDoc(
      key: 'dependsOn',
      type: 'String?',
      description: 'Another key that must be truthy for this to apply.',
      required: false,
    ),
    FieldDoc(
      key: 'min',
      type: 'number',
      description: 'Minimum allowed value (for kind="slider").',
      required: false,
    ),
    FieldDoc(
      key: 'max',
      type: 'number',
      description: 'Maximum allowed value (for kind="slider").',
      required: false,
    ),
    FieldDoc(
      key: 'step',
      type: 'number',
      description: 'Increment step (for kind="slider").',
      required: false,
    ),
    FieldDoc(
      key: 'choices',
      type: 'string[]',
      description: 'Explicit allowed values (for kind="select").',
      required: false,
    ),
  ],
);

final pluginManifest = TableDoc(
  name: 'PluginManifest',
  description: 'Metadata table every plugin must export.',
  fields: [
    FieldDoc(
      key: 'id',
      type: 'string',
      description: 'Unique plugin identifier.',
      required: true,
    ),
    FieldDoc(
      key: 'name',
      type: 'string',
      description: 'Human-readable display name.',
      required: true,
    ),
    FieldDoc(
      key: 'version',
      type: 'string',
      description: 'Semantic version string.',
      required: true,
    ),
    FieldDoc(
      key: 'description',
      type: 'String?',
      description: 'Short summary of the plugin.',
      required: false,
    ),
    FieldDoc(
      key: 'author',
      type: 'String?',
      description: 'Plugin author name or handle.',
      required: false,
    ),
    FieldDoc(
      key: 'extensionPoints',
      type: 'string[]',
      description: 'Extension point IDs this plugin hooks into.',
      required: false,
    ),
    FieldDoc(
      key: 'capabilities',
      type: 'string[]',
      description: 'Runtime capabilities required (e.g. "audio", "fs").',
      required: false,
    ),
    FieldDoc(
      key: 'dependencies',
      type: 'string[]',
      description: 'Other plugin IDs this depends on.',
      required: false,
    ),
    FieldDoc(
      key: 'isCore',
      type: 'boolean',
      description: 'Whether this is a core/built-in plugin.',
      required: false,
    ),
    FieldDoc(
      key: 'enabledByDefault',
      type: 'boolean',
      description: 'Whether active without explicit enabling.',
      required: false,
    ),
    FieldDoc(
      key: 'settings',
      type: 'SettingsEntry[]',
      description: 'User-configurable settings.',
      required: false,
    ),
    FieldDoc(
      key: 'thresholds',
      type: 'table',
      description: 'Runtime metrics thresholds.',
      required: false,
    ),
    FieldDoc(
      key: 'featureFlags',
      type: 'table',
      description: 'Feature flag overrides.',
      required: false,
    ),
  ],
);

final colorPalette = TableDoc(
  name: 'ColorScheme',
  description: 'UI colour palette definition.',
  fields: [
    FieldDoc(
      key: 'primary',
      type: 'string',
      description: 'Primary brand colour (hex).',
      required: false,
      defaultValue: '#6366f1',
    ),
    FieldDoc(
      key: 'background',
      type: 'string',
      description: 'Background colour (hex).',
      required: false,
      defaultValue: '#18181b',
    ),
    FieldDoc(
      key: 'text',
      type: 'string',
      description: 'Text colour (hex).',
      required: false,
      defaultValue: '#e4e4e7',
    ),
    FieldDoc(
      key: 'accent',
      type: 'string',
      description: 'Accent colour for highlights (hex).',
      required: false,
      defaultValue: '#22c55e',
    ),
  ],
);
