name: lualike_hooks_example_dart
description: Example Dart CLI app using lualike_hooks build hook.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  lualike:
    path: ../../lualike

dev_dependencies:
  lualike_hooks:
    path: ../
  hooks: ^2.0.2
  lints: ^5.0.0
  test: ^1.24.0
