# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["master"]
  pull_request:
defaults:
  run:
    working-directory: pkgs/lualike
jobs:
  dart-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.5"
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk == 'beta' && 'beta' || 'stable' }}
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - run: dart format --output=none --set-exit-if-changed .
        if: matrix.sdk == 'stable'
      - run: dart analyze
        if: matrix.sdk == 'stable'

      - name: Run tests
        run: dart test

  extra-packages:
    name: Extra packages (file, process)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Test file_lualike
        run: dart test
        working-directory: pkgs/file_lualike

      - name: Test process_lualike
        run: dart test
        working-directory: pkgs/process_lualike
