name: Lua Test Suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
defaults:
  run:
    working-directory: pkgs/lualike
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get
      
      - name: Run lua test suite
        run: dart run tools/test.dart