name: Lua Test Suite

on:
  workflow_run:
    workflows: ["Dart"]
    types: [completed]
    branches: ["master"]
  pull_request:

defaults:
  run:
    working-directory: pkgs/lualike

jobs:
  lua-test:
    # Gate on success of Dart workflow, or allow PRs to run directly
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Run lua test suite
        run: dart run tools/test.dart --verbose
