# Publish Firehose validation results as comments on pull requests, including
# pull requests opened from forks.

name: Comment on the pull request

on:
  workflow_run:
    workflows:
      - Publish
    types:
      - completed

jobs:
  upload:
    uses: dart-lang/ecosystem/.github/workflows/post_summaries.yaml@1bdafd85bb97b331ddd683577f48a5dfa7f4cb49
    permissions:
      pull-requests: write
