# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag pattern on pub.dev: 'v{{version}}'
  workflow_run:
    workflows: ["Dart", "Lua Test Suite"]
    types: [completed]
    branches: ["master"]
defaults:
  run:
    working-directory: pkgs/lualike
# Publish using custom workflow
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.ref_type == 'tag' }}
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: dart pub publish --force
