name: Deploy Dart Web App to Pages

on:
  workflow_run:
    workflows: ["Lua Test Suite"]   # <-- depend on Lua Test Suite only
    types: [completed]
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    # Run only when Lua Test Suite succeeded, or when manually dispatched
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/lualike
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub global activate webdev
      - run: dart pub get
      - name: Build web app
        run: webdev build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pkgs/lualike/build/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
